// Code generated by ent, DO NOT EDIT.

package refundwebhookevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the refundwebhookevent type in the database.
	Label = "refund_webhook_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldGateway holds the string denoting the gateway field in the database.
	FieldGateway = "gateway"
	// FieldGatewayEventID holds the string denoting the gateway_event_id field in the database.
	FieldGatewayEventID = "gateway_event_id"
	// FieldRawPayload holds the string denoting the raw_payload field in the database.
	FieldRawPayload = "raw_payload"
	// FieldProcessed holds the string denoting the processed field in the database.
	FieldProcessed = "processed"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldMatchedRefundID holds the string denoting the matched_refund_id field in the database.
	FieldMatchedRefundID = "matched_refund_id"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// Table holds the table name of the refundwebhookevent in the database.
	Table = "refund_webhook_events"
)

// Columns holds all SQL columns for refundwebhookevent fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldEnvironmentID,
	FieldGateway,
	FieldGatewayEventID,
	FieldRawPayload,
	FieldProcessed,
	FieldProcessedAt,
	FieldMatchedRefundID,
	FieldAttempts,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnvironmentID holds the default value on creation for the "environment_id" field.
	DefaultEnvironmentID string
	// GatewayValidator is a validator for the "gateway" field. It is called by the builders before save.
	GatewayValidator func(string) error
	// GatewayEventIDValidator is a validator for the "gateway_event_id" field. It is called by the builders before save.
	GatewayEventIDValidator func(string) error
	// DefaultProcessed holds the default value on creation for the "processed" field.
	DefaultProcessed bool
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
)

// OrderOption defines the ordering options for the RefundWebhookEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByGateway orders the results by the gateway field.
func ByGateway(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGateway, opts...).ToFunc()
}

// ByGatewayEventID orders the results by the gateway_event_id field.
func ByGatewayEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayEventID, opts...).ToFunc()
}

// ByProcessed orders the results by the processed field.
func ByProcessed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessed, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByMatchedRefundID orders the results by the matched_refund_id field.
func ByMatchedRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedRefundID, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}
