// Code generated by ent, DO NOT EDIT.

package refundwebhookevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldEnvironmentID, v))
}

// Gateway applies equality check predicate on the "gateway" field. It's identical to GatewayEQ.
func Gateway(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldGateway, v))
}

// GatewayEventID applies equality check predicate on the "gateway_event_id" field. It's identical to GatewayEventIDEQ.
func GatewayEventID(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldGatewayEventID, v))
}

// Processed applies equality check predicate on the "processed" field. It's identical to ProcessedEQ.
func Processed(v bool) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldProcessed, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// MatchedRefundID applies equality check predicate on the "matched_refund_id" field. It's identical to MatchedRefundIDEQ.
func MatchedRefundID(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldMatchedRefundID, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldAttempts, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// GatewayEQ applies the EQ predicate on the "gateway" field.
func GatewayEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldGateway, v))
}

// GatewayNEQ applies the NEQ predicate on the "gateway" field.
func GatewayNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldGateway, v))
}

// GatewayIn applies the In predicate on the "gateway" field.
func GatewayIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldGateway, vs...))
}

// GatewayNotIn applies the NotIn predicate on the "gateway" field.
func GatewayNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldGateway, vs...))
}

// GatewayGT applies the GT predicate on the "gateway" field.
func GatewayGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldGateway, v))
}

// GatewayGTE applies the GTE predicate on the "gateway" field.
func GatewayGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldGateway, v))
}

// GatewayLT applies the LT predicate on the "gateway" field.
func GatewayLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldGateway, v))
}

// GatewayLTE applies the LTE predicate on the "gateway" field.
func GatewayLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldGateway, v))
}

// GatewayContains applies the Contains predicate on the "gateway" field.
func GatewayContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldGateway, v))
}

// GatewayHasPrefix applies the HasPrefix predicate on the "gateway" field.
func GatewayHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldGateway, v))
}

// GatewayHasSuffix applies the HasSuffix predicate on the "gateway" field.
func GatewayHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldGateway, v))
}

// GatewayEqualFold applies the EqualFold predicate on the "gateway" field.
func GatewayEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldGateway, v))
}

// GatewayContainsFold applies the ContainsFold predicate on the "gateway" field.
func GatewayContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldGateway, v))
}

// GatewayEventIDEQ applies the EQ predicate on the "gateway_event_id" field.
func GatewayEventIDEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldGatewayEventID, v))
}

// GatewayEventIDNEQ applies the NEQ predicate on the "gateway_event_id" field.
func GatewayEventIDNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldGatewayEventID, v))
}

// GatewayEventIDIn applies the In predicate on the "gateway_event_id" field.
func GatewayEventIDIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldGatewayEventID, vs...))
}

// GatewayEventIDNotIn applies the NotIn predicate on the "gateway_event_id" field.
func GatewayEventIDNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldGatewayEventID, vs...))
}

// GatewayEventIDGT applies the GT predicate on the "gateway_event_id" field.
func GatewayEventIDGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldGatewayEventID, v))
}

// GatewayEventIDGTE applies the GTE predicate on the "gateway_event_id" field.
func GatewayEventIDGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldGatewayEventID, v))
}

// GatewayEventIDLT applies the LT predicate on the "gateway_event_id" field.
func GatewayEventIDLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldGatewayEventID, v))
}

// GatewayEventIDLTE applies the LTE predicate on the "gateway_event_id" field.
func GatewayEventIDLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldGatewayEventID, v))
}

// GatewayEventIDContains applies the Contains predicate on the "gateway_event_id" field.
func GatewayEventIDContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldGatewayEventID, v))
}

// GatewayEventIDHasPrefix applies the HasPrefix predicate on the "gateway_event_id" field.
func GatewayEventIDHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldGatewayEventID, v))
}

// GatewayEventIDHasSuffix applies the HasSuffix predicate on the "gateway_event_id" field.
func GatewayEventIDHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldGatewayEventID, v))
}

// GatewayEventIDEqualFold applies the EqualFold predicate on the "gateway_event_id" field.
func GatewayEventIDEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldGatewayEventID, v))
}

// GatewayEventIDContainsFold applies the ContainsFold predicate on the "gateway_event_id" field.
func GatewayEventIDContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldGatewayEventID, v))
}

// ProcessedEQ applies the EQ predicate on the "processed" field.
func ProcessedEQ(v bool) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldProcessed, v))
}

// ProcessedNEQ applies the NEQ predicate on the "processed" field.
func ProcessedNEQ(v bool) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldProcessed, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotNull(FieldProcessedAt))
}

// MatchedRefundIDEQ applies the EQ predicate on the "matched_refund_id" field.
func MatchedRefundIDEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldMatchedRefundID, v))
}

// MatchedRefundIDNEQ applies the NEQ predicate on the "matched_refund_id" field.
func MatchedRefundIDNEQ(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldMatchedRefundID, v))
}

// MatchedRefundIDIn applies the In predicate on the "matched_refund_id" field.
func MatchedRefundIDIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldMatchedRefundID, vs...))
}

// MatchedRefundIDNotIn applies the NotIn predicate on the "matched_refund_id" field.
func MatchedRefundIDNotIn(vs ...string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldMatchedRefundID, vs...))
}

// MatchedRefundIDGT applies the GT predicate on the "matched_refund_id" field.
func MatchedRefundIDGT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldMatchedRefundID, v))
}

// MatchedRefundIDGTE applies the GTE predicate on the "matched_refund_id" field.
func MatchedRefundIDGTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldMatchedRefundID, v))
}

// MatchedRefundIDLT applies the LT predicate on the "matched_refund_id" field.
func MatchedRefundIDLT(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldMatchedRefundID, v))
}

// MatchedRefundIDLTE applies the LTE predicate on the "matched_refund_id" field.
func MatchedRefundIDLTE(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldMatchedRefundID, v))
}

// MatchedRefundIDContains applies the Contains predicate on the "matched_refund_id" field.
func MatchedRefundIDContains(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContains(FieldMatchedRefundID, v))
}

// MatchedRefundIDHasPrefix applies the HasPrefix predicate on the "matched_refund_id" field.
func MatchedRefundIDHasPrefix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasPrefix(FieldMatchedRefundID, v))
}

// MatchedRefundIDHasSuffix applies the HasSuffix predicate on the "matched_refund_id" field.
func MatchedRefundIDHasSuffix(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldHasSuffix(FieldMatchedRefundID, v))
}

// MatchedRefundIDIsNil applies the IsNil predicate on the "matched_refund_id" field.
func MatchedRefundIDIsNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIsNull(FieldMatchedRefundID))
}

// MatchedRefundIDNotNil applies the NotNil predicate on the "matched_refund_id" field.
func MatchedRefundIDNotNil() predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotNull(FieldMatchedRefundID))
}

// MatchedRefundIDEqualFold applies the EqualFold predicate on the "matched_refund_id" field.
func MatchedRefundIDEqualFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEqualFold(FieldMatchedRefundID, v))
}

// MatchedRefundIDContainsFold applies the ContainsFold predicate on the "matched_refund_id" field.
func MatchedRefundIDContainsFold(v string) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldContainsFold(FieldMatchedRefundID, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.FieldLTE(FieldAttempts, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RefundWebhookEvent) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RefundWebhookEvent) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RefundWebhookEvent) predicate.RefundWebhookEvent {
	return predicate.RefundWebhookEvent(sql.NotPredicates(p))
}
