// Code generated by ent, DO NOT EDIT.

package systemevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldEnvironmentID, v))
}

// WebhookMessageID applies equality check predicate on the "webhook_message_id" field. It's identical to WebhookMessageIDEQ.
func WebhookMessageID(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldWebhookMessageID, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldPublishedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// WebhookMessageIDEQ applies the EQ predicate on the "webhook_message_id" field.
func WebhookMessageIDEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldWebhookMessageID, v))
}

// WebhookMessageIDNEQ applies the NEQ predicate on the "webhook_message_id" field.
func WebhookMessageIDNEQ(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldWebhookMessageID, v))
}

// WebhookMessageIDIn applies the In predicate on the "webhook_message_id" field.
func WebhookMessageIDIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldWebhookMessageID, vs...))
}

// WebhookMessageIDNotIn applies the NotIn predicate on the "webhook_message_id" field.
func WebhookMessageIDNotIn(vs ...string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldWebhookMessageID, vs...))
}

// WebhookMessageIDGT applies the GT predicate on the "webhook_message_id" field.
func WebhookMessageIDGT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldWebhookMessageID, v))
}

// WebhookMessageIDGTE applies the GTE predicate on the "webhook_message_id" field.
func WebhookMessageIDGTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldWebhookMessageID, v))
}

// WebhookMessageIDLT applies the LT predicate on the "webhook_message_id" field.
func WebhookMessageIDLT(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldWebhookMessageID, v))
}

// WebhookMessageIDLTE applies the LTE predicate on the "webhook_message_id" field.
func WebhookMessageIDLTE(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldWebhookMessageID, v))
}

// WebhookMessageIDContains applies the Contains predicate on the "webhook_message_id" field.
func WebhookMessageIDContains(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContains(FieldWebhookMessageID, v))
}

// WebhookMessageIDHasPrefix applies the HasPrefix predicate on the "webhook_message_id" field.
func WebhookMessageIDHasPrefix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasPrefix(FieldWebhookMessageID, v))
}

// WebhookMessageIDHasSuffix applies the HasSuffix predicate on the "webhook_message_id" field.
func WebhookMessageIDHasSuffix(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldHasSuffix(FieldWebhookMessageID, v))
}

// WebhookMessageIDIsNil applies the IsNil predicate on the "webhook_message_id" field.
func WebhookMessageIDIsNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIsNull(FieldWebhookMessageID))
}

// WebhookMessageIDNotNil applies the NotNil predicate on the "webhook_message_id" field.
func WebhookMessageIDNotNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotNull(FieldWebhookMessageID))
}

// WebhookMessageIDEqualFold applies the EqualFold predicate on the "webhook_message_id" field.
func WebhookMessageIDEqualFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEqualFold(FieldWebhookMessageID, v))
}

// WebhookMessageIDContainsFold applies the ContainsFold predicate on the "webhook_message_id" field.
func WebhookMessageIDContainsFold(v string) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldContainsFold(FieldWebhookMessageID, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotNull(FieldPublishedAt))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.SystemEvent {
	return predicate.SystemEvent(sql.FieldNotNull(FieldPayload))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemEvent) predicate.SystemEvent {
	return predicate.SystemEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemEvent) predicate.SystemEvent {
	return predicate.SystemEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemEvent) predicate.SystemEvent {
	return predicate.SystemEvent(sql.NotPredicates(p))
}
