// Code generated by ent, DO NOT EDIT.

package creditapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldEnvironmentID, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldEntityID, v))
}

// EntityType applies equality check predicate on the "entity_type" field. It's identical to EntityTypeEQ.
func EntityType(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldEntityType, v))
}

// CreditsAmount applies equality check predicate on the "credits_amount" field. It's identical to CreditsAmountEQ.
func CreditsAmount(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCreditsAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCurrency, v))
}

// WalletTransactionID applies equality check predicate on the "wallet_transaction_id" field. It's identical to WalletTransactionIDEQ.
func WalletTransactionID(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldWalletTransactionID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldEntityID, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityTypeGT applies the GT predicate on the "entity_type" field.
func EntityTypeGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldEntityType, v))
}

// EntityTypeGTE applies the GTE predicate on the "entity_type" field.
func EntityTypeGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldEntityType, v))
}

// EntityTypeLT applies the LT predicate on the "entity_type" field.
func EntityTypeLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldEntityType, v))
}

// EntityTypeLTE applies the LTE predicate on the "entity_type" field.
func EntityTypeLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldEntityType, v))
}

// EntityTypeContains applies the Contains predicate on the "entity_type" field.
func EntityTypeContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldEntityType, v))
}

// EntityTypeHasPrefix applies the HasPrefix predicate on the "entity_type" field.
func EntityTypeHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldEntityType, v))
}

// EntityTypeHasSuffix applies the HasSuffix predicate on the "entity_type" field.
func EntityTypeHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldEntityType, v))
}

// EntityTypeEqualFold applies the EqualFold predicate on the "entity_type" field.
func EntityTypeEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldEntityType, v))
}

// EntityTypeContainsFold applies the ContainsFold predicate on the "entity_type" field.
func EntityTypeContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldEntityType, v))
}

// CreditsAmountEQ applies the EQ predicate on the "credits_amount" field.
func CreditsAmountEQ(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCreditsAmount, v))
}

// CreditsAmountNEQ applies the NEQ predicate on the "credits_amount" field.
func CreditsAmountNEQ(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldCreditsAmount, v))
}

// CreditsAmountIn applies the In predicate on the "credits_amount" field.
func CreditsAmountIn(vs ...decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldCreditsAmount, vs...))
}

// CreditsAmountNotIn applies the NotIn predicate on the "credits_amount" field.
func CreditsAmountNotIn(vs ...decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldCreditsAmount, vs...))
}

// CreditsAmountGT applies the GT predicate on the "credits_amount" field.
func CreditsAmountGT(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldCreditsAmount, v))
}

// CreditsAmountGTE applies the GTE predicate on the "credits_amount" field.
func CreditsAmountGTE(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldCreditsAmount, v))
}

// CreditsAmountLT applies the LT predicate on the "credits_amount" field.
func CreditsAmountLT(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldCreditsAmount, v))
}

// CreditsAmountLTE applies the LTE predicate on the "credits_amount" field.
func CreditsAmountLTE(v decimal.Decimal) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldCreditsAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldCurrency, v))
}

// WalletTransactionIDEQ applies the EQ predicate on the "wallet_transaction_id" field.
func WalletTransactionIDEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEQ(FieldWalletTransactionID, v))
}

// WalletTransactionIDNEQ applies the NEQ predicate on the "wallet_transaction_id" field.
func WalletTransactionIDNEQ(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNEQ(FieldWalletTransactionID, v))
}

// WalletTransactionIDIn applies the In predicate on the "wallet_transaction_id" field.
func WalletTransactionIDIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIn(FieldWalletTransactionID, vs...))
}

// WalletTransactionIDNotIn applies the NotIn predicate on the "wallet_transaction_id" field.
func WalletTransactionIDNotIn(vs ...string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotIn(FieldWalletTransactionID, vs...))
}

// WalletTransactionIDGT applies the GT predicate on the "wallet_transaction_id" field.
func WalletTransactionIDGT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGT(FieldWalletTransactionID, v))
}

// WalletTransactionIDGTE applies the GTE predicate on the "wallet_transaction_id" field.
func WalletTransactionIDGTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldGTE(FieldWalletTransactionID, v))
}

// WalletTransactionIDLT applies the LT predicate on the "wallet_transaction_id" field.
func WalletTransactionIDLT(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLT(FieldWalletTransactionID, v))
}

// WalletTransactionIDLTE applies the LTE predicate on the "wallet_transaction_id" field.
func WalletTransactionIDLTE(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldLTE(FieldWalletTransactionID, v))
}

// WalletTransactionIDContains applies the Contains predicate on the "wallet_transaction_id" field.
func WalletTransactionIDContains(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContains(FieldWalletTransactionID, v))
}

// WalletTransactionIDHasPrefix applies the HasPrefix predicate on the "wallet_transaction_id" field.
func WalletTransactionIDHasPrefix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasPrefix(FieldWalletTransactionID, v))
}

// WalletTransactionIDHasSuffix applies the HasSuffix predicate on the "wallet_transaction_id" field.
func WalletTransactionIDHasSuffix(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldHasSuffix(FieldWalletTransactionID, v))
}

// WalletTransactionIDIsNil applies the IsNil predicate on the "wallet_transaction_id" field.
func WalletTransactionIDIsNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldIsNull(FieldWalletTransactionID))
}

// WalletTransactionIDNotNil applies the NotNil predicate on the "wallet_transaction_id" field.
func WalletTransactionIDNotNil() predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldNotNull(FieldWalletTransactionID))
}

// WalletTransactionIDEqualFold applies the EqualFold predicate on the "wallet_transaction_id" field.
func WalletTransactionIDEqualFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldEqualFold(FieldWalletTransactionID, v))
}

// WalletTransactionIDContainsFold applies the ContainsFold predicate on the "wallet_transaction_id" field.
func WalletTransactionIDContainsFold(v string) predicate.CreditApplication {
	return predicate.CreditApplication(sql.FieldContainsFold(FieldWalletTransactionID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreditApplication) predicate.CreditApplication {
	return predicate.CreditApplication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreditApplication) predicate.CreditApplication {
	return predicate.CreditApplication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreditApplication) predicate.CreditApplication {
	return predicate.CreditApplication(sql.NotPredicates(p))
}
