// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/creditapplication"
	"github.com/shopspring/decimal"
)

// CreditApplicationCreate is the builder for creating a CreditApplication entity.
type CreditApplicationCreate struct {
	config
	mutation *CreditApplicationMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (cac *CreditApplicationCreate) SetTenantID(s string) *CreditApplicationCreate {
	cac.mutation.SetTenantID(s)
	return cac
}

// SetStatus sets the "status" field.
func (cac *CreditApplicationCreate) SetStatus(s string) *CreditApplicationCreate {
	cac.mutation.SetStatus(s)
	return cac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableStatus(s *string) *CreditApplicationCreate {
	if s != nil {
		cac.SetStatus(*s)
	}
	return cac
}

// SetCreatedAt sets the "created_at" field.
func (cac *CreditApplicationCreate) SetCreatedAt(t time.Time) *CreditApplicationCreate {
	cac.mutation.SetCreatedAt(t)
	return cac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableCreatedAt(t *time.Time) *CreditApplicationCreate {
	if t != nil {
		cac.SetCreatedAt(*t)
	}
	return cac
}

// SetUpdatedAt sets the "updated_at" field.
func (cac *CreditApplicationCreate) SetUpdatedAt(t time.Time) *CreditApplicationCreate {
	cac.mutation.SetUpdatedAt(t)
	return cac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableUpdatedAt(t *time.Time) *CreditApplicationCreate {
	if t != nil {
		cac.SetUpdatedAt(*t)
	}
	return cac
}

// SetCreatedBy sets the "created_by" field.
func (cac *CreditApplicationCreate) SetCreatedBy(s string) *CreditApplicationCreate {
	cac.mutation.SetCreatedBy(s)
	return cac
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableCreatedBy(s *string) *CreditApplicationCreate {
	if s != nil {
		cac.SetCreatedBy(*s)
	}
	return cac
}

// SetUpdatedBy sets the "updated_by" field.
func (cac *CreditApplicationCreate) SetUpdatedBy(s string) *CreditApplicationCreate {
	cac.mutation.SetUpdatedBy(s)
	return cac
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableUpdatedBy(s *string) *CreditApplicationCreate {
	if s != nil {
		cac.SetUpdatedBy(*s)
	}
	return cac
}

// SetEnvironmentID sets the "environment_id" field.
func (cac *CreditApplicationCreate) SetEnvironmentID(s string) *CreditApplicationCreate {
	cac.mutation.SetEnvironmentID(s)
	return cac
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableEnvironmentID(s *string) *CreditApplicationCreate {
	if s != nil {
		cac.SetEnvironmentID(*s)
	}
	return cac
}

// SetEntityID sets the "entity_id" field.
func (cac *CreditApplicationCreate) SetEntityID(s string) *CreditApplicationCreate {
	cac.mutation.SetEntityID(s)
	return cac
}

// SetEntityType sets the "entity_type" field.
func (cac *CreditApplicationCreate) SetEntityType(s string) *CreditApplicationCreate {
	cac.mutation.SetEntityType(s)
	return cac
}

// SetCreditsAmount sets the "credits_amount" field.
func (cac *CreditApplicationCreate) SetCreditsAmount(d decimal.Decimal) *CreditApplicationCreate {
	cac.mutation.SetCreditsAmount(d)
	return cac
}

// SetCurrency sets the "currency" field.
func (cac *CreditApplicationCreate) SetCurrency(s string) *CreditApplicationCreate {
	cac.mutation.SetCurrency(s)
	return cac
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (cac *CreditApplicationCreate) SetWalletTransactionID(s string) *CreditApplicationCreate {
	cac.mutation.SetWalletTransactionID(s)
	return cac
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (cac *CreditApplicationCreate) SetNillableWalletTransactionID(s *string) *CreditApplicationCreate {
	if s != nil {
		cac.SetWalletTransactionID(*s)
	}
	return cac
}

// SetID sets the "id" field.
func (cac *CreditApplicationCreate) SetID(s string) *CreditApplicationCreate {
	cac.mutation.SetID(s)
	return cac
}

// Mutation returns the CreditApplicationMutation object of the builder.
func (cac *CreditApplicationCreate) Mutation() *CreditApplicationMutation {
	return cac.mutation
}

// Save creates the CreditApplication in the database.
func (cac *CreditApplicationCreate) Save(ctx context.Context) (*CreditApplication, error) {
	cac.defaults()
	return withHooks(ctx, cac.sqlSave, cac.mutation, cac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cac *CreditApplicationCreate) SaveX(ctx context.Context) *CreditApplication {
	v, err := cac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cac *CreditApplicationCreate) Exec(ctx context.Context) error {
	_, err := cac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cac *CreditApplicationCreate) ExecX(ctx context.Context) {
	if err := cac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cac *CreditApplicationCreate) defaults() {
	if _, ok := cac.mutation.Status(); !ok {
		v := creditapplication.DefaultStatus
		cac.mutation.SetStatus(v)
	}
	if _, ok := cac.mutation.CreatedAt(); !ok {
		v := creditapplication.DefaultCreatedAt()
		cac.mutation.SetCreatedAt(v)
	}
	if _, ok := cac.mutation.UpdatedAt(); !ok {
		v := creditapplication.DefaultUpdatedAt()
		cac.mutation.SetUpdatedAt(v)
	}
	if _, ok := cac.mutation.EnvironmentID(); !ok {
		v := creditapplication.DefaultEnvironmentID
		cac.mutation.SetEnvironmentID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cac *CreditApplicationCreate) check() error {
	if _, ok := cac.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CreditApplication.tenant_id"`)}
	}
	if v, ok := cac.mutation.TenantID(); ok {
		if err := creditapplication.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.tenant_id": %w`, err)}
		}
	}
	if _, ok := cac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CreditApplication.status"`)}
	}
	if _, ok := cac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreditApplication.created_at"`)}
	}
	if _, ok := cac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CreditApplication.updated_at"`)}
	}
	if _, ok := cac.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "CreditApplication.entity_id"`)}
	}
	if v, ok := cac.mutation.EntityID(); ok {
		if err := creditapplication.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.entity_id": %w`, err)}
		}
	}
	if _, ok := cac.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "CreditApplication.entity_type"`)}
	}
	if v, ok := cac.mutation.EntityType(); ok {
		if err := creditapplication.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.entity_type": %w`, err)}
		}
	}
	if _, ok := cac.mutation.CreditsAmount(); !ok {
		return &ValidationError{Name: "credits_amount", err: errors.New(`ent: missing required field "CreditApplication.credits_amount"`)}
	}
	if _, ok := cac.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CreditApplication.currency"`)}
	}
	if v, ok := cac.mutation.Currency(); ok {
		if err := creditapplication.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.currency": %w`, err)}
		}
	}
	return nil
}

func (cac *CreditApplicationCreate) sqlSave(ctx context.Context) (*CreditApplication, error) {
	if err := cac.check(); err != nil {
		return nil, err
	}
	_node, _spec := cac.createSpec()
	if err := sqlgraph.CreateNode(ctx, cac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CreditApplication.ID type: %T", _spec.ID.Value)
		}
	}
	cac.mutation.id = &_node.ID
	cac.mutation.done = true
	return _node, nil
}

func (cac *CreditApplicationCreate) createSpec() (*CreditApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditApplication{config: cac.config}
		_spec = sqlgraph.NewCreateSpec(creditapplication.Table, sqlgraph.NewFieldSpec(creditapplication.FieldID, field.TypeString))
	)
	if id, ok := cac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cac.mutation.TenantID(); ok {
		_spec.SetField(creditapplication.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := cac.mutation.Status(); ok {
		_spec.SetField(creditapplication.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := cac.mutation.CreatedAt(); ok {
		_spec.SetField(creditapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cac.mutation.UpdatedAt(); ok {
		_spec.SetField(creditapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cac.mutation.CreatedBy(); ok {
		_spec.SetField(creditapplication.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := cac.mutation.UpdatedBy(); ok {
		_spec.SetField(creditapplication.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := cac.mutation.EnvironmentID(); ok {
		_spec.SetField(creditapplication.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := cac.mutation.EntityID(); ok {
		_spec.SetField(creditapplication.FieldEntityID, field.TypeString, value)
		_node.EntityID = value
	}
	if value, ok := cac.mutation.EntityType(); ok {
		_spec.SetField(creditapplication.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := cac.mutation.CreditsAmount(); ok {
		_spec.SetField(creditapplication.FieldCreditsAmount, field.TypeOther, value)
		_node.CreditsAmount = value
	}
	if value, ok := cac.mutation.Currency(); ok {
		_spec.SetField(creditapplication.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := cac.mutation.WalletTransactionID(); ok {
		_spec.SetField(creditapplication.FieldWalletTransactionID, field.TypeString, value)
		_node.WalletTransactionID = &value
	}
	return _node, _spec
}

// CreditApplicationCreateBulk is the builder for creating many CreditApplication entities in bulk.
type CreditApplicationCreateBulk struct {
	config
	err      error
	builders []*CreditApplicationCreate
}

// Save creates the CreditApplication entities in the database.
func (cacb *CreditApplicationCreateBulk) Save(ctx context.Context) ([]*CreditApplication, error) {
	if cacb.err != nil {
		return nil, cacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cacb.builders))
	nodes := make([]*CreditApplication, len(cacb.builders))
	mutators := make([]Mutator, len(cacb.builders))
	for i := range cacb.builders {
		func(i int, root context.Context) {
			builder := cacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cacb *CreditApplicationCreateBulk) SaveX(ctx context.Context) []*CreditApplication {
	v, err := cacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cacb *CreditApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := cacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cacb *CreditApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := cacb.Exec(ctx); err != nil {
		panic(err)
	}
}
