// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/creditapplication"
	"github.com/flexprice/flexprice/ent/predicate"
)

// CreditApplicationDelete is the builder for deleting a CreditApplication entity.
type CreditApplicationDelete struct {
	config
	hooks    []Hook
	mutation *CreditApplicationMutation
}

// Where appends a list predicates to the CreditApplicationDelete builder.
func (cad *CreditApplicationDelete) Where(ps ...predicate.CreditApplication) *CreditApplicationDelete {
	cad.mutation.Where(ps...)
	return cad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cad *CreditApplicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cad.sqlExec, cad.mutation, cad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cad *CreditApplicationDelete) ExecX(ctx context.Context) int {
	n, err := cad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cad *CreditApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(creditapplication.Table, sqlgraph.NewFieldSpec(creditapplication.FieldID, field.TypeString))
	if ps := cad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cad.mutation.done = true
	return affected, err
}

// CreditApplicationDeleteOne is the builder for deleting a single CreditApplication entity.
type CreditApplicationDeleteOne struct {
	cad *CreditApplicationDelete
}

// Where appends a list predicates to the CreditApplicationDelete builder.
func (cado *CreditApplicationDeleteOne) Where(ps ...predicate.CreditApplication) *CreditApplicationDeleteOne {
	cado.cad.mutation.Where(ps...)
	return cado
}

// Exec executes the deletion query.
func (cado *CreditApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := cado.cad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{creditapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cado *CreditApplicationDeleteOne) ExecX(ctx context.Context) {
	if err := cado.Exec(ctx); err != nil {
		panic(err)
	}
}
