// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/creditapplication"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/shopspring/decimal"
)

// CreditApplicationUpdate is the builder for updating CreditApplication entities.
type CreditApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *CreditApplicationMutation
}

// Where appends a list predicates to the CreditApplicationUpdate builder.
func (cau *CreditApplicationUpdate) Where(ps ...predicate.CreditApplication) *CreditApplicationUpdate {
	cau.mutation.Where(ps...)
	return cau
}

// SetStatus sets the "status" field.
func (cau *CreditApplicationUpdate) SetStatus(s string) *CreditApplicationUpdate {
	cau.mutation.SetStatus(s)
	return cau
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableStatus(s *string) *CreditApplicationUpdate {
	if s != nil {
		cau.SetStatus(*s)
	}
	return cau
}

// SetUpdatedAt sets the "updated_at" field.
func (cau *CreditApplicationUpdate) SetUpdatedAt(t time.Time) *CreditApplicationUpdate {
	cau.mutation.SetUpdatedAt(t)
	return cau
}

// SetUpdatedBy sets the "updated_by" field.
func (cau *CreditApplicationUpdate) SetUpdatedBy(s string) *CreditApplicationUpdate {
	cau.mutation.SetUpdatedBy(s)
	return cau
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableUpdatedBy(s *string) *CreditApplicationUpdate {
	if s != nil {
		cau.SetUpdatedBy(*s)
	}
	return cau
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cau *CreditApplicationUpdate) ClearUpdatedBy() *CreditApplicationUpdate {
	cau.mutation.ClearUpdatedBy()
	return cau
}

// SetEntityID sets the "entity_id" field.
func (cau *CreditApplicationUpdate) SetEntityID(s string) *CreditApplicationUpdate {
	cau.mutation.SetEntityID(s)
	return cau
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableEntityID(s *string) *CreditApplicationUpdate {
	if s != nil {
		cau.SetEntityID(*s)
	}
	return cau
}

// SetEntityType sets the "entity_type" field.
func (cau *CreditApplicationUpdate) SetEntityType(s string) *CreditApplicationUpdate {
	cau.mutation.SetEntityType(s)
	return cau
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableEntityType(s *string) *CreditApplicationUpdate {
	if s != nil {
		cau.SetEntityType(*s)
	}
	return cau
}

// SetCreditsAmount sets the "credits_amount" field.
func (cau *CreditApplicationUpdate) SetCreditsAmount(d decimal.Decimal) *CreditApplicationUpdate {
	cau.mutation.SetCreditsAmount(d)
	return cau
}

// SetNillableCreditsAmount sets the "credits_amount" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableCreditsAmount(d *decimal.Decimal) *CreditApplicationUpdate {
	if d != nil {
		cau.SetCreditsAmount(*d)
	}
	return cau
}

// SetCurrency sets the "currency" field.
func (cau *CreditApplicationUpdate) SetCurrency(s string) *CreditApplicationUpdate {
	cau.mutation.SetCurrency(s)
	return cau
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableCurrency(s *string) *CreditApplicationUpdate {
	if s != nil {
		cau.SetCurrency(*s)
	}
	return cau
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (cau *CreditApplicationUpdate) SetWalletTransactionID(s string) *CreditApplicationUpdate {
	cau.mutation.SetWalletTransactionID(s)
	return cau
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (cau *CreditApplicationUpdate) SetNillableWalletTransactionID(s *string) *CreditApplicationUpdate {
	if s != nil {
		cau.SetWalletTransactionID(*s)
	}
	return cau
}

// ClearWalletTransactionID clears the value of the "wallet_transaction_id" field.
func (cau *CreditApplicationUpdate) ClearWalletTransactionID() *CreditApplicationUpdate {
	cau.mutation.ClearWalletTransactionID()
	return cau
}

// Mutation returns the CreditApplicationMutation object of the builder.
func (cau *CreditApplicationUpdate) Mutation() *CreditApplicationMutation {
	return cau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cau *CreditApplicationUpdate) Save(ctx context.Context) (int, error) {
	cau.defaults()
	return withHooks(ctx, cau.sqlSave, cau.mutation, cau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cau *CreditApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := cau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cau *CreditApplicationUpdate) Exec(ctx context.Context) error {
	_, err := cau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cau *CreditApplicationUpdate) ExecX(ctx context.Context) {
	if err := cau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cau *CreditApplicationUpdate) defaults() {
	if _, ok := cau.mutation.UpdatedAt(); !ok {
		v := creditapplication.UpdateDefaultUpdatedAt()
		cau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cau *CreditApplicationUpdate) check() error {
	if v, ok := cau.mutation.EntityID(); ok {
		if err := creditapplication.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.entity_id": %w`, err)}
		}
	}
	if v, ok := cau.mutation.EntityType(); ok {
		if err := creditapplication.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.entity_type": %w`, err)}
		}
	}
	if v, ok := cau.mutation.Currency(); ok {
		if err := creditapplication.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.currency": %w`, err)}
		}
	}
	return nil
}

func (cau *CreditApplicationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(creditapplication.Table, creditapplication.Columns, sqlgraph.NewFieldSpec(creditapplication.FieldID, field.TypeString))
	if ps := cau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cau.mutation.Status(); ok {
		_spec.SetField(creditapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := cau.mutation.UpdatedAt(); ok {
		_spec.SetField(creditapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if cau.mutation.CreatedByCleared() {
		_spec.ClearField(creditapplication.FieldCreatedBy, field.TypeString)
	}
	if value, ok := cau.mutation.UpdatedBy(); ok {
		_spec.SetField(creditapplication.FieldUpdatedBy, field.TypeString, value)
	}
	if cau.mutation.UpdatedByCleared() {
		_spec.ClearField(creditapplication.FieldUpdatedBy, field.TypeString)
	}
	if cau.mutation.EnvironmentIDCleared() {
		_spec.ClearField(creditapplication.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := cau.mutation.EntityID(); ok {
		_spec.SetField(creditapplication.FieldEntityID, field.TypeString, value)
	}
	if value, ok := cau.mutation.EntityType(); ok {
		_spec.SetField(creditapplication.FieldEntityType, field.TypeString, value)
	}
	if value, ok := cau.mutation.CreditsAmount(); ok {
		_spec.SetField(creditapplication.FieldCreditsAmount, field.TypeOther, value)
	}
	if value, ok := cau.mutation.Currency(); ok {
		_spec.SetField(creditapplication.FieldCurrency, field.TypeString, value)
	}
	if value, ok := cau.mutation.WalletTransactionID(); ok {
		_spec.SetField(creditapplication.FieldWalletTransactionID, field.TypeString, value)
	}
	if cau.mutation.WalletTransactionIDCleared() {
		_spec.ClearField(creditapplication.FieldWalletTransactionID, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creditapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cau.mutation.done = true
	return n, nil
}

// CreditApplicationUpdateOne is the builder for updating a single CreditApplication entity.
type CreditApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreditApplicationMutation
}

// SetStatus sets the "status" field.
func (cauo *CreditApplicationUpdateOne) SetStatus(s string) *CreditApplicationUpdateOne {
	cauo.mutation.SetStatus(s)
	return cauo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableStatus(s *string) *CreditApplicationUpdateOne {
	if s != nil {
		cauo.SetStatus(*s)
	}
	return cauo
}

// SetUpdatedAt sets the "updated_at" field.
func (cauo *CreditApplicationUpdateOne) SetUpdatedAt(t time.Time) *CreditApplicationUpdateOne {
	cauo.mutation.SetUpdatedAt(t)
	return cauo
}

// SetUpdatedBy sets the "updated_by" field.
func (cauo *CreditApplicationUpdateOne) SetUpdatedBy(s string) *CreditApplicationUpdateOne {
	cauo.mutation.SetUpdatedBy(s)
	return cauo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableUpdatedBy(s *string) *CreditApplicationUpdateOne {
	if s != nil {
		cauo.SetUpdatedBy(*s)
	}
	return cauo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cauo *CreditApplicationUpdateOne) ClearUpdatedBy() *CreditApplicationUpdateOne {
	cauo.mutation.ClearUpdatedBy()
	return cauo
}

// SetEntityID sets the "entity_id" field.
func (cauo *CreditApplicationUpdateOne) SetEntityID(s string) *CreditApplicationUpdateOne {
	cauo.mutation.SetEntityID(s)
	return cauo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableEntityID(s *string) *CreditApplicationUpdateOne {
	if s != nil {
		cauo.SetEntityID(*s)
	}
	return cauo
}

// SetEntityType sets the "entity_type" field.
func (cauo *CreditApplicationUpdateOne) SetEntityType(s string) *CreditApplicationUpdateOne {
	cauo.mutation.SetEntityType(s)
	return cauo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableEntityType(s *string) *CreditApplicationUpdateOne {
	if s != nil {
		cauo.SetEntityType(*s)
	}
	return cauo
}

// SetCreditsAmount sets the "credits_amount" field.
func (cauo *CreditApplicationUpdateOne) SetCreditsAmount(d decimal.Decimal) *CreditApplicationUpdateOne {
	cauo.mutation.SetCreditsAmount(d)
	return cauo
}

// SetNillableCreditsAmount sets the "credits_amount" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableCreditsAmount(d *decimal.Decimal) *CreditApplicationUpdateOne {
	if d != nil {
		cauo.SetCreditsAmount(*d)
	}
	return cauo
}

// SetCurrency sets the "currency" field.
func (cauo *CreditApplicationUpdateOne) SetCurrency(s string) *CreditApplicationUpdateOne {
	cauo.mutation.SetCurrency(s)
	return cauo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableCurrency(s *string) *CreditApplicationUpdateOne {
	if s != nil {
		cauo.SetCurrency(*s)
	}
	return cauo
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (cauo *CreditApplicationUpdateOne) SetWalletTransactionID(s string) *CreditApplicationUpdateOne {
	cauo.mutation.SetWalletTransactionID(s)
	return cauo
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (cauo *CreditApplicationUpdateOne) SetNillableWalletTransactionID(s *string) *CreditApplicationUpdateOne {
	if s != nil {
		cauo.SetWalletTransactionID(*s)
	}
	return cauo
}

// ClearWalletTransactionID clears the value of the "wallet_transaction_id" field.
func (cauo *CreditApplicationUpdateOne) ClearWalletTransactionID() *CreditApplicationUpdateOne {
	cauo.mutation.ClearWalletTransactionID()
	return cauo
}

// Mutation returns the CreditApplicationMutation object of the builder.
func (cauo *CreditApplicationUpdateOne) Mutation() *CreditApplicationMutation {
	return cauo.mutation
}

// Where appends a list predicates to the CreditApplicationUpdate builder.
func (cauo *CreditApplicationUpdateOne) Where(ps ...predicate.CreditApplication) *CreditApplicationUpdateOne {
	cauo.mutation.Where(ps...)
	return cauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cauo *CreditApplicationUpdateOne) Select(field string, fields ...string) *CreditApplicationUpdateOne {
	cauo.fields = append([]string{field}, fields...)
	return cauo
}

// Save executes the query and returns the updated CreditApplication entity.
func (cauo *CreditApplicationUpdateOne) Save(ctx context.Context) (*CreditApplication, error) {
	cauo.defaults()
	return withHooks(ctx, cauo.sqlSave, cauo.mutation, cauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cauo *CreditApplicationUpdateOne) SaveX(ctx context.Context) *CreditApplication {
	node, err := cauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cauo *CreditApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := cauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cauo *CreditApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := cauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cauo *CreditApplicationUpdateOne) defaults() {
	if _, ok := cauo.mutation.UpdatedAt(); !ok {
		v := creditapplication.UpdateDefaultUpdatedAt()
		cauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cauo *CreditApplicationUpdateOne) check() error {
	if v, ok := cauo.mutation.EntityID(); ok {
		if err := creditapplication.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.entity_id": %w`, err)}
		}
	}
	if v, ok := cauo.mutation.EntityType(); ok {
		if err := creditapplication.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.entity_type": %w`, err)}
		}
	}
	if v, ok := cauo.mutation.Currency(); ok {
		if err := creditapplication.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CreditApplication.currency": %w`, err)}
		}
	}
	return nil
}

func (cauo *CreditApplicationUpdateOne) sqlSave(ctx context.Context) (_node *CreditApplication, err error) {
	if err := cauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creditapplication.Table, creditapplication.Columns, sqlgraph.NewFieldSpec(creditapplication.FieldID, field.TypeString))
	id, ok := cauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreditApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creditapplication.FieldID)
		for _, f := range fields {
			if !creditapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creditapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cauo.mutation.Status(); ok {
		_spec.SetField(creditapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := cauo.mutation.UpdatedAt(); ok {
		_spec.SetField(creditapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if cauo.mutation.CreatedByCleared() {
		_spec.ClearField(creditapplication.FieldCreatedBy, field.TypeString)
	}
	if value, ok := cauo.mutation.UpdatedBy(); ok {
		_spec.SetField(creditapplication.FieldUpdatedBy, field.TypeString, value)
	}
	if cauo.mutation.UpdatedByCleared() {
		_spec.ClearField(creditapplication.FieldUpdatedBy, field.TypeString)
	}
	if cauo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(creditapplication.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := cauo.mutation.EntityID(); ok {
		_spec.SetField(creditapplication.FieldEntityID, field.TypeString, value)
	}
	if value, ok := cauo.mutation.EntityType(); ok {
		_spec.SetField(creditapplication.FieldEntityType, field.TypeString, value)
	}
	if value, ok := cauo.mutation.CreditsAmount(); ok {
		_spec.SetField(creditapplication.FieldCreditsAmount, field.TypeOther, value)
	}
	if value, ok := cauo.mutation.Currency(); ok {
		_spec.SetField(creditapplication.FieldCurrency, field.TypeString, value)
	}
	if value, ok := cauo.mutation.WalletTransactionID(); ok {
		_spec.SetField(creditapplication.FieldWalletTransactionID, field.TypeString, value)
	}
	if cauo.mutation.WalletTransactionIDCleared() {
		_spec.ClearField(creditapplication.FieldWalletTransactionID, field.TypeString)
	}
	_node = &CreditApplication{config: cauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creditapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cauo.mutation.done = true
	return _node, nil
}
