// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/creditapplication"
	"github.com/flexprice/flexprice/ent/predicate"
)

// CreditApplicationQuery is the builder for querying CreditApplication entities.
type CreditApplicationQuery struct {
	config
	ctx        *QueryContext
	order      []creditapplication.OrderOption
	inters     []Interceptor
	predicates []predicate.CreditApplication
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CreditApplicationQuery builder.
func (caq *CreditApplicationQuery) Where(ps ...predicate.CreditApplication) *CreditApplicationQuery {
	caq.predicates = append(caq.predicates, ps...)
	return caq
}

// Limit the number of records to be returned by this query.
func (caq *CreditApplicationQuery) Limit(limit int) *CreditApplicationQuery {
	caq.ctx.Limit = &limit
	return caq
}

// Offset to start from.
func (caq *CreditApplicationQuery) Offset(offset int) *CreditApplicationQuery {
	caq.ctx.Offset = &offset
	return caq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (caq *CreditApplicationQuery) Unique(unique bool) *CreditApplicationQuery {
	caq.ctx.Unique = &unique
	return caq
}

// Order specifies how the records should be ordered.
func (caq *CreditApplicationQuery) Order(o ...creditapplication.OrderOption) *CreditApplicationQuery {
	caq.order = append(caq.order, o...)
	return caq
}

// First returns the first CreditApplication entity from the query.
// Returns a *NotFoundError when no CreditApplication was found.
func (caq *CreditApplicationQuery) First(ctx context.Context) (*CreditApplication, error) {
	nodes, err := caq.Limit(1).All(setContextOp(ctx, caq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{creditapplication.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (caq *CreditApplicationQuery) FirstX(ctx context.Context) *CreditApplication {
	node, err := caq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CreditApplication ID from the query.
// Returns a *NotFoundError when no CreditApplication ID was found.
func (caq *CreditApplicationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = caq.Limit(1).IDs(setContextOp(ctx, caq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{creditapplication.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (caq *CreditApplicationQuery) FirstIDX(ctx context.Context) string {
	id, err := caq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CreditApplication entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CreditApplication entity is found.
// Returns a *NotFoundError when no CreditApplication entities are found.
func (caq *CreditApplicationQuery) Only(ctx context.Context) (*CreditApplication, error) {
	nodes, err := caq.Limit(2).All(setContextOp(ctx, caq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{creditapplication.Label}
	default:
		return nil, &NotSingularError{creditapplication.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (caq *CreditApplicationQuery) OnlyX(ctx context.Context) *CreditApplication {
	node, err := caq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CreditApplication ID in the query.
// Returns a *NotSingularError when more than one CreditApplication ID is found.
// Returns a *NotFoundError when no entities are found.
func (caq *CreditApplicationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = caq.Limit(2).IDs(setContextOp(ctx, caq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{creditapplication.Label}
	default:
		err = &NotSingularError{creditapplication.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (caq *CreditApplicationQuery) OnlyIDX(ctx context.Context) string {
	id, err := caq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CreditApplications.
func (caq *CreditApplicationQuery) All(ctx context.Context) ([]*CreditApplication, error) {
	ctx = setContextOp(ctx, caq.ctx, ent.OpQueryAll)
	if err := caq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CreditApplication, *CreditApplicationQuery]()
	return withInterceptors[[]*CreditApplication](ctx, caq, qr, caq.inters)
}

// AllX is like All, but panics if an error occurs.
func (caq *CreditApplicationQuery) AllX(ctx context.Context) []*CreditApplication {
	nodes, err := caq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CreditApplication IDs.
func (caq *CreditApplicationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if caq.ctx.Unique == nil && caq.path != nil {
		caq.Unique(true)
	}
	ctx = setContextOp(ctx, caq.ctx, ent.OpQueryIDs)
	if err = caq.Select(creditapplication.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (caq *CreditApplicationQuery) IDsX(ctx context.Context) []string {
	ids, err := caq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (caq *CreditApplicationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, caq.ctx, ent.OpQueryCount)
	if err := caq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, caq, querierCount[*CreditApplicationQuery](), caq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (caq *CreditApplicationQuery) CountX(ctx context.Context) int {
	count, err := caq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (caq *CreditApplicationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, caq.ctx, ent.OpQueryExist)
	switch _, err := caq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (caq *CreditApplicationQuery) ExistX(ctx context.Context) bool {
	exist, err := caq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CreditApplicationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (caq *CreditApplicationQuery) Clone() *CreditApplicationQuery {
	if caq == nil {
		return nil
	}
	return &CreditApplicationQuery{
		config:     caq.config,
		ctx:        caq.ctx.Clone(),
		order:      append([]creditapplication.OrderOption{}, caq.order...),
		inters:     append([]Interceptor{}, caq.inters...),
		predicates: append([]predicate.CreditApplication{}, caq.predicates...),
		// clone intermediate query.
		sql:  caq.sql.Clone(),
		path: caq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CreditApplication.Query().
//		GroupBy(creditapplication.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (caq *CreditApplicationQuery) GroupBy(field string, fields ...string) *CreditApplicationGroupBy {
	caq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CreditApplicationGroupBy{build: caq}
	grbuild.flds = &caq.ctx.Fields
	grbuild.label = creditapplication.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.CreditApplication.Query().
//		Select(creditapplication.FieldTenantID).
//		Scan(ctx, &v)
func (caq *CreditApplicationQuery) Select(fields ...string) *CreditApplicationSelect {
	caq.ctx.Fields = append(caq.ctx.Fields, fields...)
	sbuild := &CreditApplicationSelect{CreditApplicationQuery: caq}
	sbuild.label = creditapplication.Label
	sbuild.flds, sbuild.scan = &caq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CreditApplicationSelect configured with the given aggregations.
func (caq *CreditApplicationQuery) Aggregate(fns ...AggregateFunc) *CreditApplicationSelect {
	return caq.Select().Aggregate(fns...)
}

func (caq *CreditApplicationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range caq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, caq); err != nil {
				return err
			}
		}
	}
	for _, f := range caq.ctx.Fields {
		if !creditapplication.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if caq.path != nil {
		prev, err := caq.path(ctx)
		if err != nil {
			return err
		}
		caq.sql = prev
	}
	return nil
}

func (caq *CreditApplicationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CreditApplication, error) {
	var (
		nodes = []*CreditApplication{}
		_spec = caq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CreditApplication).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CreditApplication{config: caq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, caq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (caq *CreditApplicationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := caq.querySpec()
	_spec.Node.Columns = caq.ctx.Fields
	if len(caq.ctx.Fields) > 0 {
		_spec.Unique = caq.ctx.Unique != nil && *caq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, caq.driver, _spec)
}

func (caq *CreditApplicationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(creditapplication.Table, creditapplication.Columns, sqlgraph.NewFieldSpec(creditapplication.FieldID, field.TypeString))
	_spec.From = caq.sql
	if unique := caq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if caq.path != nil {
		_spec.Unique = true
	}
	if fields := caq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creditapplication.FieldID)
		for i := range fields {
			if fields[i] != creditapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := caq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := caq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := caq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := caq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (caq *CreditApplicationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(caq.driver.Dialect())
	t1 := builder.Table(creditapplication.Table)
	columns := caq.ctx.Fields
	if len(columns) == 0 {
		columns = creditapplication.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if caq.sql != nil {
		selector = caq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if caq.ctx.Unique != nil && *caq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range caq.predicates {
		p(selector)
	}
	for _, p := range caq.order {
		p(selector)
	}
	if offset := caq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := caq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CreditApplicationGroupBy is the group-by builder for CreditApplication entities.
type CreditApplicationGroupBy struct {
	selector
	build *CreditApplicationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cagb *CreditApplicationGroupBy) Aggregate(fns ...AggregateFunc) *CreditApplicationGroupBy {
	cagb.fns = append(cagb.fns, fns...)
	return cagb
}

// Scan applies the selector query and scans the result into the given value.
func (cagb *CreditApplicationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cagb.build.ctx, ent.OpQueryGroupBy)
	if err := cagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreditApplicationQuery, *CreditApplicationGroupBy](ctx, cagb.build, cagb, cagb.build.inters, v)
}

func (cagb *CreditApplicationGroupBy) sqlScan(ctx context.Context, root *CreditApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cagb.fns))
	for _, fn := range cagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cagb.flds)+len(cagb.fns))
		for _, f := range *cagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CreditApplicationSelect is the builder for selecting fields of CreditApplication entities.
type CreditApplicationSelect struct {
	*CreditApplicationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cas *CreditApplicationSelect) Aggregate(fns ...AggregateFunc) *CreditApplicationSelect {
	cas.fns = append(cas.fns, fns...)
	return cas
}

// Scan applies the selector query and scans the result into the given value.
func (cas *CreditApplicationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cas.ctx, ent.OpQuerySelect)
	if err := cas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreditApplicationQuery, *CreditApplicationSelect](ctx, cas.CreditApplicationQuery, cas, cas.inters, v)
}

func (cas *CreditApplicationSelect) sqlScan(ctx context.Context, root *CreditApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cas.fns))
	for _, fn := range cas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
