// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/creditapplication"
	"github.com/shopspring/decimal"
)

// CreditApplication is the model entity for the CreditApplication schema.
type CreditApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// ID of the entity this credit is applied to (invoice, invoice_line_item, etc.)
	EntityID string `json:"entity_id,omitempty"`
	// Type of entity: INVOICE, INVOICE_LINE_ITEM, TRANSACTION, WALLET, etc.
	EntityType string `json:"entity_type,omitempty"`
	// Amount of credits applied
	CreditsAmount decimal.Decimal `json:"credits_amount,omitempty"`
	// Currency of the credit application
	Currency string `json:"currency,omitempty"`
	// Wallet transaction ID that was debited for this credit application
	WalletTransactionID *string `json:"wallet_transaction_id,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creditapplication.FieldCreditsAmount:
			values[i] = new(decimal.Decimal)
		case creditapplication.FieldID, creditapplication.FieldTenantID, creditapplication.FieldStatus, creditapplication.FieldCreatedBy, creditapplication.FieldUpdatedBy, creditapplication.FieldEnvironmentID, creditapplication.FieldEntityID, creditapplication.FieldEntityType, creditapplication.FieldCurrency, creditapplication.FieldWalletTransactionID:
			values[i] = new(sql.NullString)
		case creditapplication.FieldCreatedAt, creditapplication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditApplication fields.
func (ca *CreditApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creditapplication.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ca.ID = value.String
			}
		case creditapplication.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				ca.TenantID = value.String
			}
		case creditapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ca.Status = value.String
			}
		case creditapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ca.CreatedAt = value.Time
			}
		case creditapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ca.UpdatedAt = value.Time
			}
		case creditapplication.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				ca.CreatedBy = value.String
			}
		case creditapplication.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				ca.UpdatedBy = value.String
			}
		case creditapplication.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				ca.EnvironmentID = value.String
			}
		case creditapplication.FieldEntityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				ca.EntityID = value.String
			}
		case creditapplication.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				ca.EntityType = value.String
			}
		case creditapplication.FieldCreditsAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field credits_amount", values[i])
			} else if value != nil {
				ca.CreditsAmount = *value
			}
		case creditapplication.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				ca.Currency = value.String
			}
		case creditapplication.FieldWalletTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_transaction_id", values[i])
			} else if value.Valid {
				ca.WalletTransactionID = new(string)
				*ca.WalletTransactionID = value.String
			}
		default:
			ca.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditApplication.
// This includes values selected through modifiers, order, etc.
func (ca *CreditApplication) Value(name string) (ent.Value, error) {
	return ca.selectValues.Get(name)
}

// Update returns a builder for updating this CreditApplication.
// Note that you need to call CreditApplication.Unwrap() before calling this method if this CreditApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (ca *CreditApplication) Update() *CreditApplicationUpdateOne {
	return NewCreditApplicationClient(ca.config).UpdateOne(ca)
}

// Unwrap unwraps the CreditApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ca *CreditApplication) Unwrap() *CreditApplication {
	_tx, ok := ca.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditApplication is not a transactional entity")
	}
	ca.config.driver = _tx.drv
	return ca
}

// String implements the fmt.Stringer.
func (ca *CreditApplication) String() string {
	var builder strings.Builder
	builder.WriteString("CreditApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ca.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(ca.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ca.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ca.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ca.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(ca.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(ca.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(ca.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(ca.EntityID)
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(ca.EntityType)
	builder.WriteString(", ")
	builder.WriteString("credits_amount=")
	builder.WriteString(fmt.Sprintf("%v", ca.CreditsAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(ca.Currency)
	builder.WriteString(", ")
	if v := ca.WalletTransactionID; v != nil {
		builder.WriteString("wallet_transaction_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CreditApplications is a parsable slice of CreditApplication.
type CreditApplications []*CreditApplication
