// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/integrationentity"
	"github.com/flexprice/flexprice/ent/predicate"
)

// IntegrationEntityDelete is the builder for deleting a IntegrationEntity entity.
type IntegrationEntityDelete struct {
	config
	hooks    []Hook
	mutation *IntegrationEntityMutation
}

// Where appends a list predicates to the IntegrationEntityDelete builder.
func (ied *IntegrationEntityDelete) Where(ps ...predicate.IntegrationEntity) *IntegrationEntityDelete {
	ied.mutation.Where(ps...)
	return ied
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ied *IntegrationEntityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ied.sqlExec, ied.mutation, ied.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ied *IntegrationEntityDelete) ExecX(ctx context.Context) int {
	n, err := ied.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ied *IntegrationEntityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(integrationentity.Table, sqlgraph.NewFieldSpec(integrationentity.FieldID, field.TypeString))
	if ps := ied.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ied.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ied.mutation.done = true
	return affected, err
}

// IntegrationEntityDeleteOne is the builder for deleting a single IntegrationEntity entity.
type IntegrationEntityDeleteOne struct {
	ied *IntegrationEntityDelete
}

// Where appends a list predicates to the IntegrationEntityDelete builder.
func (iedo *IntegrationEntityDeleteOne) Where(ps ...predicate.IntegrationEntity) *IntegrationEntityDeleteOne {
	iedo.ied.mutation.Where(ps...)
	return iedo
}

// Exec executes the deletion query.
func (iedo *IntegrationEntityDeleteOne) Exec(ctx context.Context) error {
	n, err := iedo.ied.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{integrationentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iedo *IntegrationEntityDeleteOne) ExecX(ctx context.Context) {
	if err := iedo.Exec(ctx); err != nil {
		panic(err)
	}
}
