// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/refundwebhookevent"
)

// RefundWebhookEventUpdate is the builder for updating RefundWebhookEvent entities.
type RefundWebhookEventUpdate struct {
	config
	hooks    []Hook
	mutation *RefundWebhookEventMutation
}

// Where appends a list predicates to the RefundWebhookEventUpdate builder.
func (rweu *RefundWebhookEventUpdate) Where(ps ...predicate.RefundWebhookEvent) *RefundWebhookEventUpdate {
	rweu.mutation.Where(ps...)
	return rweu
}

// SetStatus sets the "status" field.
func (rweu *RefundWebhookEventUpdate) SetStatus(s string) *RefundWebhookEventUpdate {
	rweu.mutation.SetStatus(s)
	return rweu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rweu *RefundWebhookEventUpdate) SetNillableStatus(s *string) *RefundWebhookEventUpdate {
	if s != nil {
		rweu.SetStatus(*s)
	}
	return rweu
}

// SetUpdatedAt sets the "updated_at" field.
func (rweu *RefundWebhookEventUpdate) SetUpdatedAt(t time.Time) *RefundWebhookEventUpdate {
	rweu.mutation.SetUpdatedAt(t)
	return rweu
}

// SetUpdatedBy sets the "updated_by" field.
func (rweu *RefundWebhookEventUpdate) SetUpdatedBy(s string) *RefundWebhookEventUpdate {
	rweu.mutation.SetUpdatedBy(s)
	return rweu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (rweu *RefundWebhookEventUpdate) SetNillableUpdatedBy(s *string) *RefundWebhookEventUpdate {
	if s != nil {
		rweu.SetUpdatedBy(*s)
	}
	return rweu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (rweu *RefundWebhookEventUpdate) ClearUpdatedBy() *RefundWebhookEventUpdate {
	rweu.mutation.ClearUpdatedBy()
	return rweu
}

// SetRawPayload sets the "raw_payload" field.
func (rweu *RefundWebhookEventUpdate) SetRawPayload(m map[string]interface{}) *RefundWebhookEventUpdate {
	rweu.mutation.SetRawPayload(m)
	return rweu
}

// SetProcessed sets the "processed" field.
func (rweu *RefundWebhookEventUpdate) SetProcessed(b bool) *RefundWebhookEventUpdate {
	rweu.mutation.SetProcessed(b)
	return rweu
}

// SetNillableProcessed sets the "processed" field if the given value is not nil.
func (rweu *RefundWebhookEventUpdate) SetNillableProcessed(b *bool) *RefundWebhookEventUpdate {
	if b != nil {
		rweu.SetProcessed(*b)
	}
	return rweu
}

// SetProcessedAt sets the "processed_at" field.
func (rweu *RefundWebhookEventUpdate) SetProcessedAt(t time.Time) *RefundWebhookEventUpdate {
	rweu.mutation.SetProcessedAt(t)
	return rweu
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (rweu *RefundWebhookEventUpdate) SetNillableProcessedAt(t *time.Time) *RefundWebhookEventUpdate {
	if t != nil {
		rweu.SetProcessedAt(*t)
	}
	return rweu
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (rweu *RefundWebhookEventUpdate) ClearProcessedAt() *RefundWebhookEventUpdate {
	rweu.mutation.ClearProcessedAt()
	return rweu
}

// SetMatchedRefundID sets the "matched_refund_id" field.
func (rweu *RefundWebhookEventUpdate) SetMatchedRefundID(s string) *RefundWebhookEventUpdate {
	rweu.mutation.SetMatchedRefundID(s)
	return rweu
}

// SetNillableMatchedRefundID sets the "matched_refund_id" field if the given value is not nil.
func (rweu *RefundWebhookEventUpdate) SetNillableMatchedRefundID(s *string) *RefundWebhookEventUpdate {
	if s != nil {
		rweu.SetMatchedRefundID(*s)
	}
	return rweu
}

// ClearMatchedRefundID clears the value of the "matched_refund_id" field.
func (rweu *RefundWebhookEventUpdate) ClearMatchedRefundID() *RefundWebhookEventUpdate {
	rweu.mutation.ClearMatchedRefundID()
	return rweu
}

// SetAttempts sets the "attempts" field.
func (rweu *RefundWebhookEventUpdate) SetAttempts(i int) *RefundWebhookEventUpdate {
	rweu.mutation.ResetAttempts()
	rweu.mutation.SetAttempts(i)
	return rweu
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (rweu *RefundWebhookEventUpdate) SetNillableAttempts(i *int) *RefundWebhookEventUpdate {
	if i != nil {
		rweu.SetAttempts(*i)
	}
	return rweu
}

// AddAttempts adds i to the "attempts" field.
func (rweu *RefundWebhookEventUpdate) AddAttempts(i int) *RefundWebhookEventUpdate {
	rweu.mutation.AddAttempts(i)
	return rweu
}

// Mutation returns the RefundWebhookEventMutation object of the builder.
func (rweu *RefundWebhookEventUpdate) Mutation() *RefundWebhookEventMutation {
	return rweu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rweu *RefundWebhookEventUpdate) Save(ctx context.Context) (int, error) {
	rweu.defaults()
	return withHooks(ctx, rweu.sqlSave, rweu.mutation, rweu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rweu *RefundWebhookEventUpdate) SaveX(ctx context.Context) int {
	affected, err := rweu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rweu *RefundWebhookEventUpdate) Exec(ctx context.Context) error {
	_, err := rweu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rweu *RefundWebhookEventUpdate) ExecX(ctx context.Context) {
	if err := rweu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rweu *RefundWebhookEventUpdate) defaults() {
	if _, ok := rweu.mutation.UpdatedAt(); !ok {
		v := refundwebhookevent.UpdateDefaultUpdatedAt()
		rweu.mutation.SetUpdatedAt(v)
	}
}

func (rweu *RefundWebhookEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(refundwebhookevent.Table, refundwebhookevent.Columns, sqlgraph.NewFieldSpec(refundwebhookevent.FieldID, field.TypeString))
	if ps := rweu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rweu.mutation.Status(); ok {
		_spec.SetField(refundwebhookevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := rweu.mutation.UpdatedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if rweu.mutation.CreatedByCleared() {
		_spec.ClearField(refundwebhookevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := rweu.mutation.UpdatedBy(); ok {
		_spec.SetField(refundwebhookevent.FieldUpdatedBy, field.TypeString, value)
	}
	if rweu.mutation.UpdatedByCleared() {
		_spec.ClearField(refundwebhookevent.FieldUpdatedBy, field.TypeString)
	}
	if rweu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(refundwebhookevent.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := rweu.mutation.RawPayload(); ok {
		_spec.SetField(refundwebhookevent.FieldRawPayload, field.TypeJSON, value)
	}
	if value, ok := rweu.mutation.Processed(); ok {
		_spec.SetField(refundwebhookevent.FieldProcessed, field.TypeBool, value)
	}
	if value, ok := rweu.mutation.ProcessedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldProcessedAt, field.TypeTime, value)
	}
	if rweu.mutation.ProcessedAtCleared() {
		_spec.ClearField(refundwebhookevent.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := rweu.mutation.MatchedRefundID(); ok {
		_spec.SetField(refundwebhookevent.FieldMatchedRefundID, field.TypeString, value)
	}
	if rweu.mutation.MatchedRefundIDCleared() {
		_spec.ClearField(refundwebhookevent.FieldMatchedRefundID, field.TypeString)
	}
	if value, ok := rweu.mutation.Attempts(); ok {
		_spec.SetField(refundwebhookevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := rweu.mutation.AddedAttempts(); ok {
		_spec.AddField(refundwebhookevent.FieldAttempts, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rweu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refundwebhookevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rweu.mutation.done = true
	return n, nil
}

// RefundWebhookEventUpdateOne is the builder for updating a single RefundWebhookEvent entity.
type RefundWebhookEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefundWebhookEventMutation
}

// SetStatus sets the "status" field.
func (rweuo *RefundWebhookEventUpdateOne) SetStatus(s string) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetStatus(s)
	return rweuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rweuo *RefundWebhookEventUpdateOne) SetNillableStatus(s *string) *RefundWebhookEventUpdateOne {
	if s != nil {
		rweuo.SetStatus(*s)
	}
	return rweuo
}

// SetUpdatedAt sets the "updated_at" field.
func (rweuo *RefundWebhookEventUpdateOne) SetUpdatedAt(t time.Time) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetUpdatedAt(t)
	return rweuo
}

// SetUpdatedBy sets the "updated_by" field.
func (rweuo *RefundWebhookEventUpdateOne) SetUpdatedBy(s string) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetUpdatedBy(s)
	return rweuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (rweuo *RefundWebhookEventUpdateOne) SetNillableUpdatedBy(s *string) *RefundWebhookEventUpdateOne {
	if s != nil {
		rweuo.SetUpdatedBy(*s)
	}
	return rweuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (rweuo *RefundWebhookEventUpdateOne) ClearUpdatedBy() *RefundWebhookEventUpdateOne {
	rweuo.mutation.ClearUpdatedBy()
	return rweuo
}

// SetRawPayload sets the "raw_payload" field.
func (rweuo *RefundWebhookEventUpdateOne) SetRawPayload(m map[string]interface{}) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetRawPayload(m)
	return rweuo
}

// SetProcessed sets the "processed" field.
func (rweuo *RefundWebhookEventUpdateOne) SetProcessed(b bool) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetProcessed(b)
	return rweuo
}

// SetNillableProcessed sets the "processed" field if the given value is not nil.
func (rweuo *RefundWebhookEventUpdateOne) SetNillableProcessed(b *bool) *RefundWebhookEventUpdateOne {
	if b != nil {
		rweuo.SetProcessed(*b)
	}
	return rweuo
}

// SetProcessedAt sets the "processed_at" field.
func (rweuo *RefundWebhookEventUpdateOne) SetProcessedAt(t time.Time) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetProcessedAt(t)
	return rweuo
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (rweuo *RefundWebhookEventUpdateOne) SetNillableProcessedAt(t *time.Time) *RefundWebhookEventUpdateOne {
	if t != nil {
		rweuo.SetProcessedAt(*t)
	}
	return rweuo
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (rweuo *RefundWebhookEventUpdateOne) ClearProcessedAt() *RefundWebhookEventUpdateOne {
	rweuo.mutation.ClearProcessedAt()
	return rweuo
}

// SetMatchedRefundID sets the "matched_refund_id" field.
func (rweuo *RefundWebhookEventUpdateOne) SetMatchedRefundID(s string) *RefundWebhookEventUpdateOne {
	rweuo.mutation.SetMatchedRefundID(s)
	return rweuo
}

// SetNillableMatchedRefundID sets the "matched_refund_id" field if the given value is not nil.
func (rweuo *RefundWebhookEventUpdateOne) SetNillableMatchedRefundID(s *string) *RefundWebhookEventUpdateOne {
	if s != nil {
		rweuo.SetMatchedRefundID(*s)
	}
	return rweuo
}

// ClearMatchedRefundID clears the value of the "matched_refund_id" field.
func (rweuo *RefundWebhookEventUpdateOne) ClearMatchedRefundID() *RefundWebhookEventUpdateOne {
	rweuo.mutation.ClearMatchedRefundID()
	return rweuo
}

// SetAttempts sets the "attempts" field.
func (rweuo *RefundWebhookEventUpdateOne) SetAttempts(i int) *RefundWebhookEventUpdateOne {
	rweuo.mutation.ResetAttempts()
	rweuo.mutation.SetAttempts(i)
	return rweuo
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (rweuo *RefundWebhookEventUpdateOne) SetNillableAttempts(i *int) *RefundWebhookEventUpdateOne {
	if i != nil {
		rweuo.SetAttempts(*i)
	}
	return rweuo
}

// AddAttempts adds i to the "attempts" field.
func (rweuo *RefundWebhookEventUpdateOne) AddAttempts(i int) *RefundWebhookEventUpdateOne {
	rweuo.mutation.AddAttempts(i)
	return rweuo
}

// Mutation returns the RefundWebhookEventMutation object of the builder.
func (rweuo *RefundWebhookEventUpdateOne) Mutation() *RefundWebhookEventMutation {
	return rweuo.mutation
}

// Where appends a list predicates to the RefundWebhookEventUpdate builder.
func (rweuo *RefundWebhookEventUpdateOne) Where(ps ...predicate.RefundWebhookEvent) *RefundWebhookEventUpdateOne {
	rweuo.mutation.Where(ps...)
	return rweuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rweuo *RefundWebhookEventUpdateOne) Select(field string, fields ...string) *RefundWebhookEventUpdateOne {
	rweuo.fields = append([]string{field}, fields...)
	return rweuo
}

// Save executes the query and returns the updated RefundWebhookEvent entity.
func (rweuo *RefundWebhookEventUpdateOne) Save(ctx context.Context) (*RefundWebhookEvent, error) {
	rweuo.defaults()
	return withHooks(ctx, rweuo.sqlSave, rweuo.mutation, rweuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rweuo *RefundWebhookEventUpdateOne) SaveX(ctx context.Context) *RefundWebhookEvent {
	node, err := rweuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rweuo *RefundWebhookEventUpdateOne) Exec(ctx context.Context) error {
	_, err := rweuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rweuo *RefundWebhookEventUpdateOne) ExecX(ctx context.Context) {
	if err := rweuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rweuo *RefundWebhookEventUpdateOne) defaults() {
	if _, ok := rweuo.mutation.UpdatedAt(); !ok {
		v := refundwebhookevent.UpdateDefaultUpdatedAt()
		rweuo.mutation.SetUpdatedAt(v)
	}
}

func (rweuo *RefundWebhookEventUpdateOne) sqlSave(ctx context.Context) (_node *RefundWebhookEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(refundwebhookevent.Table, refundwebhookevent.Columns, sqlgraph.NewFieldSpec(refundwebhookevent.FieldID, field.TypeString))
	id, ok := rweuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefundWebhookEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rweuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refundwebhookevent.FieldID)
		for _, f := range fields {
			if !refundwebhookevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refundwebhookevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rweuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rweuo.mutation.Status(); ok {
		_spec.SetField(refundwebhookevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := rweuo.mutation.UpdatedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if rweuo.mutation.CreatedByCleared() {
		_spec.ClearField(refundwebhookevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := rweuo.mutation.UpdatedBy(); ok {
		_spec.SetField(refundwebhookevent.FieldUpdatedBy, field.TypeString, value)
	}
	if rweuo.mutation.UpdatedByCleared() {
		_spec.ClearField(refundwebhookevent.FieldUpdatedBy, field.TypeString)
	}
	if rweuo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(refundwebhookevent.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := rweuo.mutation.RawPayload(); ok {
		_spec.SetField(refundwebhookevent.FieldRawPayload, field.TypeJSON, value)
	}
	if value, ok := rweuo.mutation.Processed(); ok {
		_spec.SetField(refundwebhookevent.FieldProcessed, field.TypeBool, value)
	}
	if value, ok := rweuo.mutation.ProcessedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldProcessedAt, field.TypeTime, value)
	}
	if rweuo.mutation.ProcessedAtCleared() {
		_spec.ClearField(refundwebhookevent.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := rweuo.mutation.MatchedRefundID(); ok {
		_spec.SetField(refundwebhookevent.FieldMatchedRefundID, field.TypeString, value)
	}
	if rweuo.mutation.MatchedRefundIDCleared() {
		_spec.ClearField(refundwebhookevent.FieldMatchedRefundID, field.TypeString)
	}
	if value, ok := rweuo.mutation.Attempts(); ok {
		_spec.SetField(refundwebhookevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := rweuo.mutation.AddedAttempts(); ok {
		_spec.AddField(refundwebhookevent.FieldAttempts, field.TypeInt, value)
	}
	_node = &RefundWebhookEvent{config: rweuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rweuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refundwebhookevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rweuo.mutation.done = true
	return _node, nil
}
