// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/refundwebhookevent"
)

// RefundWebhookEventDelete is the builder for deleting a RefundWebhookEvent entity.
type RefundWebhookEventDelete struct {
	config
	hooks    []Hook
	mutation *RefundWebhookEventMutation
}

// Where appends a list predicates to the RefundWebhookEventDelete builder.
func (rwed *RefundWebhookEventDelete) Where(ps ...predicate.RefundWebhookEvent) *RefundWebhookEventDelete {
	rwed.mutation.Where(ps...)
	return rwed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rwed *RefundWebhookEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rwed.sqlExec, rwed.mutation, rwed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rwed *RefundWebhookEventDelete) ExecX(ctx context.Context) int {
	n, err := rwed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rwed *RefundWebhookEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(refundwebhookevent.Table, sqlgraph.NewFieldSpec(refundwebhookevent.FieldID, field.TypeString))
	if ps := rwed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rwed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rwed.mutation.done = true
	return affected, err
}

// RefundWebhookEventDeleteOne is the builder for deleting a single RefundWebhookEvent entity.
type RefundWebhookEventDeleteOne struct {
	rwed *RefundWebhookEventDelete
}

// Where appends a list predicates to the RefundWebhookEventDelete builder.
func (rwedo *RefundWebhookEventDeleteOne) Where(ps ...predicate.RefundWebhookEvent) *RefundWebhookEventDeleteOne {
	rwedo.rwed.mutation.Where(ps...)
	return rwedo
}

// Exec executes the deletion query.
func (rwedo *RefundWebhookEventDeleteOne) Exec(ctx context.Context) error {
	n, err := rwedo.rwed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{refundwebhookevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rwedo *RefundWebhookEventDeleteOne) ExecX(ctx context.Context) {
	if err := rwedo.Exec(ctx); err != nil {
		panic(err)
	}
}
