// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/refundwebhookevent"
)

// RefundWebhookEventQuery is the builder for querying RefundWebhookEvent entities.
type RefundWebhookEventQuery struct {
	config
	ctx        *QueryContext
	order      []refundwebhookevent.OrderOption
	inters     []Interceptor
	predicates []predicate.RefundWebhookEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RefundWebhookEventQuery builder.
func (rweq *RefundWebhookEventQuery) Where(ps ...predicate.RefundWebhookEvent) *RefundWebhookEventQuery {
	rweq.predicates = append(rweq.predicates, ps...)
	return rweq
}

// Limit the number of records to be returned by this query.
func (rweq *RefundWebhookEventQuery) Limit(limit int) *RefundWebhookEventQuery {
	rweq.ctx.Limit = &limit
	return rweq
}

// Offset to start from.
func (rweq *RefundWebhookEventQuery) Offset(offset int) *RefundWebhookEventQuery {
	rweq.ctx.Offset = &offset
	return rweq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rweq *RefundWebhookEventQuery) Unique(unique bool) *RefundWebhookEventQuery {
	rweq.ctx.Unique = &unique
	return rweq
}

// Order specifies how the records should be ordered.
func (rweq *RefundWebhookEventQuery) Order(o ...refundwebhookevent.OrderOption) *RefundWebhookEventQuery {
	rweq.order = append(rweq.order, o...)
	return rweq
}

// First returns the first RefundWebhookEvent entity from the query.
// Returns a *NotFoundError when no RefundWebhookEvent was found.
func (rweq *RefundWebhookEventQuery) First(ctx context.Context) (*RefundWebhookEvent, error) {
	nodes, err := rweq.Limit(1).All(setContextOp(ctx, rweq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{refundwebhookevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) FirstX(ctx context.Context) *RefundWebhookEvent {
	node, err := rweq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RefundWebhookEvent ID from the query.
// Returns a *NotFoundError when no RefundWebhookEvent ID was found.
func (rweq *RefundWebhookEventQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rweq.Limit(1).IDs(setContextOp(ctx, rweq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{refundwebhookevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) FirstIDX(ctx context.Context) string {
	id, err := rweq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RefundWebhookEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RefundWebhookEvent entity is found.
// Returns a *NotFoundError when no RefundWebhookEvent entities are found.
func (rweq *RefundWebhookEventQuery) Only(ctx context.Context) (*RefundWebhookEvent, error) {
	nodes, err := rweq.Limit(2).All(setContextOp(ctx, rweq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{refundwebhookevent.Label}
	default:
		return nil, &NotSingularError{refundwebhookevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) OnlyX(ctx context.Context) *RefundWebhookEvent {
	node, err := rweq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RefundWebhookEvent ID in the query.
// Returns a *NotSingularError when more than one RefundWebhookEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (rweq *RefundWebhookEventQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rweq.Limit(2).IDs(setContextOp(ctx, rweq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{refundwebhookevent.Label}
	default:
		err = &NotSingularError{refundwebhookevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) OnlyIDX(ctx context.Context) string {
	id, err := rweq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RefundWebhookEvents.
func (rweq *RefundWebhookEventQuery) All(ctx context.Context) ([]*RefundWebhookEvent, error) {
	ctx = setContextOp(ctx, rweq.ctx, ent.OpQueryAll)
	if err := rweq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RefundWebhookEvent, *RefundWebhookEventQuery]()
	return withInterceptors[[]*RefundWebhookEvent](ctx, rweq, qr, rweq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) AllX(ctx context.Context) []*RefundWebhookEvent {
	nodes, err := rweq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RefundWebhookEvent IDs.
func (rweq *RefundWebhookEventQuery) IDs(ctx context.Context) (ids []string, err error) {
	if rweq.ctx.Unique == nil && rweq.path != nil {
		rweq.Unique(true)
	}
	ctx = setContextOp(ctx, rweq.ctx, ent.OpQueryIDs)
	if err = rweq.Select(refundwebhookevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) IDsX(ctx context.Context) []string {
	ids, err := rweq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rweq *RefundWebhookEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rweq.ctx, ent.OpQueryCount)
	if err := rweq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rweq, querierCount[*RefundWebhookEventQuery](), rweq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) CountX(ctx context.Context) int {
	count, err := rweq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rweq *RefundWebhookEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rweq.ctx, ent.OpQueryExist)
	switch _, err := rweq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rweq *RefundWebhookEventQuery) ExistX(ctx context.Context) bool {
	exist, err := rweq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RefundWebhookEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rweq *RefundWebhookEventQuery) Clone() *RefundWebhookEventQuery {
	if rweq == nil {
		return nil
	}
	return &RefundWebhookEventQuery{
		config:     rweq.config,
		ctx:        rweq.ctx.Clone(),
		order:      append([]refundwebhookevent.OrderOption{}, rweq.order...),
		inters:     append([]Interceptor{}, rweq.inters...),
		predicates: append([]predicate.RefundWebhookEvent{}, rweq.predicates...),
		// clone intermediate query.
		sql:  rweq.sql.Clone(),
		path: rweq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RefundWebhookEvent.Query().
//		GroupBy(refundwebhookevent.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rweq *RefundWebhookEventQuery) GroupBy(field string, fields ...string) *RefundWebhookEventGroupBy {
	rweq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RefundWebhookEventGroupBy{build: rweq}
	grbuild.flds = &rweq.ctx.Fields
	grbuild.label = refundwebhookevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.RefundWebhookEvent.Query().
//		Select(refundwebhookevent.FieldTenantID).
//		Scan(ctx, &v)
func (rweq *RefundWebhookEventQuery) Select(fields ...string) *RefundWebhookEventSelect {
	rweq.ctx.Fields = append(rweq.ctx.Fields, fields...)
	sbuild := &RefundWebhookEventSelect{RefundWebhookEventQuery: rweq}
	sbuild.label = refundwebhookevent.Label
	sbuild.flds, sbuild.scan = &rweq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RefundWebhookEventSelect configured with the given aggregations.
func (rweq *RefundWebhookEventQuery) Aggregate(fns ...AggregateFunc) *RefundWebhookEventSelect {
	return rweq.Select().Aggregate(fns...)
}

func (rweq *RefundWebhookEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rweq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rweq); err != nil {
				return err
			}
		}
	}
	for _, f := range rweq.ctx.Fields {
		if !refundwebhookevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rweq.path != nil {
		prev, err := rweq.path(ctx)
		if err != nil {
			return err
		}
		rweq.sql = prev
	}
	return nil
}

func (rweq *RefundWebhookEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RefundWebhookEvent, error) {
	var (
		nodes = []*RefundWebhookEvent{}
		_spec = rweq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RefundWebhookEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RefundWebhookEvent{config: rweq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rweq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rweq *RefundWebhookEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rweq.querySpec()
	_spec.Node.Columns = rweq.ctx.Fields
	if len(rweq.ctx.Fields) > 0 {
		_spec.Unique = rweq.ctx.Unique != nil && *rweq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rweq.driver, _spec)
}

func (rweq *RefundWebhookEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(refundwebhookevent.Table, refundwebhookevent.Columns, sqlgraph.NewFieldSpec(refundwebhookevent.FieldID, field.TypeString))
	_spec.From = rweq.sql
	if unique := rweq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rweq.path != nil {
		_spec.Unique = true
	}
	if fields := rweq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refundwebhookevent.FieldID)
		for i := range fields {
			if fields[i] != refundwebhookevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rweq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rweq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rweq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rweq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rweq *RefundWebhookEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rweq.driver.Dialect())
	t1 := builder.Table(refundwebhookevent.Table)
	columns := rweq.ctx.Fields
	if len(columns) == 0 {
		columns = refundwebhookevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rweq.sql != nil {
		selector = rweq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rweq.ctx.Unique != nil && *rweq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rweq.predicates {
		p(selector)
	}
	for _, p := range rweq.order {
		p(selector)
	}
	if offset := rweq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rweq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RefundWebhookEventGroupBy is the group-by builder for RefundWebhookEvent entities.
type RefundWebhookEventGroupBy struct {
	selector
	build *RefundWebhookEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rwegb *RefundWebhookEventGroupBy) Aggregate(fns ...AggregateFunc) *RefundWebhookEventGroupBy {
	rwegb.fns = append(rwegb.fns, fns...)
	return rwegb
}

// Scan applies the selector query and scans the result into the given value.
func (rwegb *RefundWebhookEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rwegb.build.ctx, ent.OpQueryGroupBy)
	if err := rwegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RefundWebhookEventQuery, *RefundWebhookEventGroupBy](ctx, rwegb.build, rwegb, rwegb.build.inters, v)
}

func (rwegb *RefundWebhookEventGroupBy) sqlScan(ctx context.Context, root *RefundWebhookEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rwegb.fns))
	for _, fn := range rwegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rwegb.flds)+len(rwegb.fns))
		for _, f := range *rwegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rwegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rwegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RefundWebhookEventSelect is the builder for selecting fields of RefundWebhookEvent entities.
type RefundWebhookEventSelect struct {
	*RefundWebhookEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rwes *RefundWebhookEventSelect) Aggregate(fns ...AggregateFunc) *RefundWebhookEventSelect {
	rwes.fns = append(rwes.fns, fns...)
	return rwes
}

// Scan applies the selector query and scans the result into the given value.
func (rwes *RefundWebhookEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rwes.ctx, ent.OpQuerySelect)
	if err := rwes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RefundWebhookEventQuery, *RefundWebhookEventSelect](ctx, rwes.RefundWebhookEventQuery, rwes, rwes.inters, v)
}

func (rwes *RefundWebhookEventSelect) sqlScan(ctx context.Context, root *RefundWebhookEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rwes.fns))
	for _, fn := range rwes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rwes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rwes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
