// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/refundwebhookevent"
)

// RefundWebhookEvent is the model entity for the RefundWebhookEvent schema.
type RefundWebhookEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// Gateway holds the value of the "gateway" field.
	Gateway string `json:"gateway,omitempty"`
	// GatewayEventID holds the value of the "gateway_event_id" field.
	GatewayEventID string `json:"gateway_event_id,omitempty"`
	// RawPayload holds the value of the "raw_payload" field.
	RawPayload map[string]interface{} `json:"raw_payload,omitempty"`
	// Processed holds the value of the "processed" field.
	Processed bool `json:"processed,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// MatchedRefundID holds the value of the "matched_refund_id" field.
	MatchedRefundID *string `json:"matched_refund_id,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts     int `json:"attempts,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RefundWebhookEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case refundwebhookevent.FieldRawPayload:
			values[i] = new([]byte)
		case refundwebhookevent.FieldProcessed:
			values[i] = new(sql.NullBool)
		case refundwebhookevent.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case refundwebhookevent.FieldID, refundwebhookevent.FieldTenantID, refundwebhookevent.FieldStatus, refundwebhookevent.FieldCreatedBy, refundwebhookevent.FieldUpdatedBy, refundwebhookevent.FieldEnvironmentID, refundwebhookevent.FieldGateway, refundwebhookevent.FieldGatewayEventID, refundwebhookevent.FieldMatchedRefundID:
			values[i] = new(sql.NullString)
		case refundwebhookevent.FieldCreatedAt, refundwebhookevent.FieldUpdatedAt, refundwebhookevent.FieldProcessedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RefundWebhookEvent fields.
func (rwe *RefundWebhookEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case refundwebhookevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				rwe.ID = value.String
			}
		case refundwebhookevent.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				rwe.TenantID = value.String
			}
		case refundwebhookevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				rwe.Status = value.String
			}
		case refundwebhookevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rwe.CreatedAt = value.Time
			}
		case refundwebhookevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rwe.UpdatedAt = value.Time
			}
		case refundwebhookevent.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				rwe.CreatedBy = value.String
			}
		case refundwebhookevent.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				rwe.UpdatedBy = value.String
			}
		case refundwebhookevent.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				rwe.EnvironmentID = value.String
			}
		case refundwebhookevent.FieldGateway:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway", values[i])
			} else if value.Valid {
				rwe.Gateway = value.String
			}
		case refundwebhookevent.FieldGatewayEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_event_id", values[i])
			} else if value.Valid {
				rwe.GatewayEventID = value.String
			}
		case refundwebhookevent.FieldRawPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rwe.RawPayload); err != nil {
					return fmt.Errorf("unmarshal field raw_payload: %w", err)
				}
			}
		case refundwebhookevent.FieldProcessed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field processed", values[i])
			} else if value.Valid {
				rwe.Processed = value.Bool
			}
		case refundwebhookevent.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				rwe.ProcessedAt = new(time.Time)
				*rwe.ProcessedAt = value.Time
			}
		case refundwebhookevent.FieldMatchedRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field matched_refund_id", values[i])
			} else if value.Valid {
				rwe.MatchedRefundID = new(string)
				*rwe.MatchedRefundID = value.String
			}
		case refundwebhookevent.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				rwe.Attempts = int(value.Int64)
			}
		default:
			rwe.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RefundWebhookEvent.
// This includes values selected through modifiers, order, etc.
func (rwe *RefundWebhookEvent) Value(name string) (ent.Value, error) {
	return rwe.selectValues.Get(name)
}

// Update returns a builder for updating this RefundWebhookEvent.
// Note that you need to call RefundWebhookEvent.Unwrap() before calling this method if this RefundWebhookEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (rwe *RefundWebhookEvent) Update() *RefundWebhookEventUpdateOne {
	return NewRefundWebhookEventClient(rwe.config).UpdateOne(rwe)
}

// Unwrap unwraps the RefundWebhookEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rwe *RefundWebhookEvent) Unwrap() *RefundWebhookEvent {
	_tx, ok := rwe.config.driver.(*txDriver)
	if !ok {
		panic("ent: RefundWebhookEvent is not a transactional entity")
	}
	rwe.config.driver = _tx.drv
	return rwe
}

// String implements the fmt.Stringer.
func (rwe *RefundWebhookEvent) String() string {
	var builder strings.Builder
	builder.WriteString("RefundWebhookEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rwe.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(rwe.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(rwe.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rwe.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rwe.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(rwe.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(rwe.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(rwe.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("gateway=")
	builder.WriteString(rwe.Gateway)
	builder.WriteString(", ")
	builder.WriteString("gateway_event_id=")
	builder.WriteString(rwe.GatewayEventID)
	builder.WriteString(", ")
	builder.WriteString("raw_payload=")
	builder.WriteString(fmt.Sprintf("%v", rwe.RawPayload))
	builder.WriteString(", ")
	builder.WriteString("processed=")
	builder.WriteString(fmt.Sprintf("%v", rwe.Processed))
	builder.WriteString(", ")
	if v := rwe.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := rwe.MatchedRefundID; v != nil {
		builder.WriteString("matched_refund_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", rwe.Attempts))
	builder.WriteByte(')')
	return builder.String()
}

// RefundWebhookEvents is a parsable slice of RefundWebhookEvent.
type RefundWebhookEvents []*RefundWebhookEvent
