// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/refundwebhookevent"
)

// RefundWebhookEventCreate is the builder for creating a RefundWebhookEvent entity.
type RefundWebhookEventCreate struct {
	config
	mutation *RefundWebhookEventMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (rwec *RefundWebhookEventCreate) SetTenantID(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetTenantID(s)
	return rwec
}

// SetStatus sets the "status" field.
func (rwec *RefundWebhookEventCreate) SetStatus(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetStatus(s)
	return rwec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableStatus(s *string) *RefundWebhookEventCreate {
	if s != nil {
		rwec.SetStatus(*s)
	}
	return rwec
}

// SetCreatedAt sets the "created_at" field.
func (rwec *RefundWebhookEventCreate) SetCreatedAt(t time.Time) *RefundWebhookEventCreate {
	rwec.mutation.SetCreatedAt(t)
	return rwec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableCreatedAt(t *time.Time) *RefundWebhookEventCreate {
	if t != nil {
		rwec.SetCreatedAt(*t)
	}
	return rwec
}

// SetUpdatedAt sets the "updated_at" field.
func (rwec *RefundWebhookEventCreate) SetUpdatedAt(t time.Time) *RefundWebhookEventCreate {
	rwec.mutation.SetUpdatedAt(t)
	return rwec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableUpdatedAt(t *time.Time) *RefundWebhookEventCreate {
	if t != nil {
		rwec.SetUpdatedAt(*t)
	}
	return rwec
}

// SetCreatedBy sets the "created_by" field.
func (rwec *RefundWebhookEventCreate) SetCreatedBy(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetCreatedBy(s)
	return rwec
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableCreatedBy(s *string) *RefundWebhookEventCreate {
	if s != nil {
		rwec.SetCreatedBy(*s)
	}
	return rwec
}

// SetUpdatedBy sets the "updated_by" field.
func (rwec *RefundWebhookEventCreate) SetUpdatedBy(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetUpdatedBy(s)
	return rwec
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableUpdatedBy(s *string) *RefundWebhookEventCreate {
	if s != nil {
		rwec.SetUpdatedBy(*s)
	}
	return rwec
}

// SetEnvironmentID sets the "environment_id" field.
func (rwec *RefundWebhookEventCreate) SetEnvironmentID(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetEnvironmentID(s)
	return rwec
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableEnvironmentID(s *string) *RefundWebhookEventCreate {
	if s != nil {
		rwec.SetEnvironmentID(*s)
	}
	return rwec
}

// SetGateway sets the "gateway" field.
func (rwec *RefundWebhookEventCreate) SetGateway(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetGateway(s)
	return rwec
}

// SetGatewayEventID sets the "gateway_event_id" field.
func (rwec *RefundWebhookEventCreate) SetGatewayEventID(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetGatewayEventID(s)
	return rwec
}

// SetRawPayload sets the "raw_payload" field.
func (rwec *RefundWebhookEventCreate) SetRawPayload(m map[string]interface{}) *RefundWebhookEventCreate {
	rwec.mutation.SetRawPayload(m)
	return rwec
}

// SetProcessed sets the "processed" field.
func (rwec *RefundWebhookEventCreate) SetProcessed(b bool) *RefundWebhookEventCreate {
	rwec.mutation.SetProcessed(b)
	return rwec
}

// SetNillableProcessed sets the "processed" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableProcessed(b *bool) *RefundWebhookEventCreate {
	if b != nil {
		rwec.SetProcessed(*b)
	}
	return rwec
}

// SetProcessedAt sets the "processed_at" field.
func (rwec *RefundWebhookEventCreate) SetProcessedAt(t time.Time) *RefundWebhookEventCreate {
	rwec.mutation.SetProcessedAt(t)
	return rwec
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableProcessedAt(t *time.Time) *RefundWebhookEventCreate {
	if t != nil {
		rwec.SetProcessedAt(*t)
	}
	return rwec
}

// SetMatchedRefundID sets the "matched_refund_id" field.
func (rwec *RefundWebhookEventCreate) SetMatchedRefundID(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetMatchedRefundID(s)
	return rwec
}

// SetNillableMatchedRefundID sets the "matched_refund_id" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableMatchedRefundID(s *string) *RefundWebhookEventCreate {
	if s != nil {
		rwec.SetMatchedRefundID(*s)
	}
	return rwec
}

// SetAttempts sets the "attempts" field.
func (rwec *RefundWebhookEventCreate) SetAttempts(i int) *RefundWebhookEventCreate {
	rwec.mutation.SetAttempts(i)
	return rwec
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (rwec *RefundWebhookEventCreate) SetNillableAttempts(i *int) *RefundWebhookEventCreate {
	if i != nil {
		rwec.SetAttempts(*i)
	}
	return rwec
}

// SetID sets the "id" field.
func (rwec *RefundWebhookEventCreate) SetID(s string) *RefundWebhookEventCreate {
	rwec.mutation.SetID(s)
	return rwec
}

// Mutation returns the RefundWebhookEventMutation object of the builder.
func (rwec *RefundWebhookEventCreate) Mutation() *RefundWebhookEventMutation {
	return rwec.mutation
}

// Save creates the RefundWebhookEvent in the database.
func (rwec *RefundWebhookEventCreate) Save(ctx context.Context) (*RefundWebhookEvent, error) {
	rwec.defaults()
	return withHooks(ctx, rwec.sqlSave, rwec.mutation, rwec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rwec *RefundWebhookEventCreate) SaveX(ctx context.Context) *RefundWebhookEvent {
	v, err := rwec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rwec *RefundWebhookEventCreate) Exec(ctx context.Context) error {
	_, err := rwec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rwec *RefundWebhookEventCreate) ExecX(ctx context.Context) {
	if err := rwec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rwec *RefundWebhookEventCreate) defaults() {
	if _, ok := rwec.mutation.Status(); !ok {
		v := refundwebhookevent.DefaultStatus
		rwec.mutation.SetStatus(v)
	}
	if _, ok := rwec.mutation.CreatedAt(); !ok {
		v := refundwebhookevent.DefaultCreatedAt()
		rwec.mutation.SetCreatedAt(v)
	}
	if _, ok := rwec.mutation.UpdatedAt(); !ok {
		v := refundwebhookevent.DefaultUpdatedAt()
		rwec.mutation.SetUpdatedAt(v)
	}
	if _, ok := rwec.mutation.EnvironmentID(); !ok {
		v := refundwebhookevent.DefaultEnvironmentID
		rwec.mutation.SetEnvironmentID(v)
	}
	if _, ok := rwec.mutation.Processed(); !ok {
		v := refundwebhookevent.DefaultProcessed
		rwec.mutation.SetProcessed(v)
	}
	if _, ok := rwec.mutation.Attempts(); !ok {
		v := refundwebhookevent.DefaultAttempts
		rwec.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rwec *RefundWebhookEventCreate) check() error {
	if _, ok := rwec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RefundWebhookEvent.tenant_id"`)}
	}
	if v, ok := rwec.mutation.TenantID(); ok {
		if err := refundwebhookevent.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "RefundWebhookEvent.tenant_id": %w`, err)}
		}
	}
	if _, ok := rwec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RefundWebhookEvent.status"`)}
	}
	if _, ok := rwec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RefundWebhookEvent.created_at"`)}
	}
	if _, ok := rwec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RefundWebhookEvent.updated_at"`)}
	}
	if _, ok := rwec.mutation.Gateway(); !ok {
		return &ValidationError{Name: "gateway", err: errors.New(`ent: missing required field "RefundWebhookEvent.gateway"`)}
	}
	if v, ok := rwec.mutation.Gateway(); ok {
		if err := refundwebhookevent.GatewayValidator(v); err != nil {
			return &ValidationError{Name: "gateway", err: fmt.Errorf(`ent: validator failed for field "RefundWebhookEvent.gateway": %w`, err)}
		}
	}
	if _, ok := rwec.mutation.GatewayEventID(); !ok {
		return &ValidationError{Name: "gateway_event_id", err: errors.New(`ent: missing required field "RefundWebhookEvent.gateway_event_id"`)}
	}
	if v, ok := rwec.mutation.GatewayEventID(); ok {
		if err := refundwebhookevent.GatewayEventIDValidator(v); err != nil {
			return &ValidationError{Name: "gateway_event_id", err: fmt.Errorf(`ent: validator failed for field "RefundWebhookEvent.gateway_event_id": %w`, err)}
		}
	}
	if _, ok := rwec.mutation.RawPayload(); !ok {
		return &ValidationError{Name: "raw_payload", err: errors.New(`ent: missing required field "RefundWebhookEvent.raw_payload"`)}
	}
	if _, ok := rwec.mutation.Processed(); !ok {
		return &ValidationError{Name: "processed", err: errors.New(`ent: missing required field "RefundWebhookEvent.processed"`)}
	}
	if _, ok := rwec.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "RefundWebhookEvent.attempts"`)}
	}
	return nil
}

func (rwec *RefundWebhookEventCreate) sqlSave(ctx context.Context) (*RefundWebhookEvent, error) {
	if err := rwec.check(); err != nil {
		return nil, err
	}
	_node, _spec := rwec.createSpec()
	if err := sqlgraph.CreateNode(ctx, rwec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RefundWebhookEvent.ID type: %T", _spec.ID.Value)
		}
	}
	rwec.mutation.id = &_node.ID
	rwec.mutation.done = true
	return _node, nil
}

func (rwec *RefundWebhookEventCreate) createSpec() (*RefundWebhookEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &RefundWebhookEvent{config: rwec.config}
		_spec = sqlgraph.NewCreateSpec(refundwebhookevent.Table, sqlgraph.NewFieldSpec(refundwebhookevent.FieldID, field.TypeString))
	)
	if id, ok := rwec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rwec.mutation.TenantID(); ok {
		_spec.SetField(refundwebhookevent.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := rwec.mutation.Status(); ok {
		_spec.SetField(refundwebhookevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := rwec.mutation.CreatedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rwec.mutation.UpdatedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rwec.mutation.CreatedBy(); ok {
		_spec.SetField(refundwebhookevent.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := rwec.mutation.UpdatedBy(); ok {
		_spec.SetField(refundwebhookevent.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := rwec.mutation.EnvironmentID(); ok {
		_spec.SetField(refundwebhookevent.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := rwec.mutation.Gateway(); ok {
		_spec.SetField(refundwebhookevent.FieldGateway, field.TypeString, value)
		_node.Gateway = value
	}
	if value, ok := rwec.mutation.GatewayEventID(); ok {
		_spec.SetField(refundwebhookevent.FieldGatewayEventID, field.TypeString, value)
		_node.GatewayEventID = value
	}
	if value, ok := rwec.mutation.RawPayload(); ok {
		_spec.SetField(refundwebhookevent.FieldRawPayload, field.TypeJSON, value)
		_node.RawPayload = value
	}
	if value, ok := rwec.mutation.Processed(); ok {
		_spec.SetField(refundwebhookevent.FieldProcessed, field.TypeBool, value)
		_node.Processed = value
	}
	if value, ok := rwec.mutation.ProcessedAt(); ok {
		_spec.SetField(refundwebhookevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := rwec.mutation.MatchedRefundID(); ok {
		_spec.SetField(refundwebhookevent.FieldMatchedRefundID, field.TypeString, value)
		_node.MatchedRefundID = &value
	}
	if value, ok := rwec.mutation.Attempts(); ok {
		_spec.SetField(refundwebhookevent.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	return _node, _spec
}

// RefundWebhookEventCreateBulk is the builder for creating many RefundWebhookEvent entities in bulk.
type RefundWebhookEventCreateBulk struct {
	config
	err      error
	builders []*RefundWebhookEventCreate
}

// Save creates the RefundWebhookEvent entities in the database.
func (rwecb *RefundWebhookEventCreateBulk) Save(ctx context.Context) ([]*RefundWebhookEvent, error) {
	if rwecb.err != nil {
		return nil, rwecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rwecb.builders))
	nodes := make([]*RefundWebhookEvent, len(rwecb.builders))
	mutators := make([]Mutator, len(rwecb.builders))
	for i := range rwecb.builders {
		func(i int, root context.Context) {
			builder := rwecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefundWebhookEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rwecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rwecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rwecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rwecb *RefundWebhookEventCreateBulk) SaveX(ctx context.Context) []*RefundWebhookEvent {
	v, err := rwecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rwecb *RefundWebhookEventCreateBulk) Exec(ctx context.Context) error {
	_, err := rwecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rwecb *RefundWebhookEventCreateBulk) ExecX(ctx context.Context) {
	if err := rwecb.Exec(ctx); err != nil {
		panic(err)
	}
}
