// Code generated by ent, DO NOT EDIT.

package integrationentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldEnvironmentID, v))
}

// EntityType applies equality check predicate on the "entity_type" field. It's identical to EntityTypeEQ.
func EntityType(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEQ(FieldEntityType, vc))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldEntityID, v))
}

// ProviderType applies equality check predicate on the "provider_type" field. It's identical to ProviderTypeEQ.
func ProviderType(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEQ(FieldProviderType, vc))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldProviderID, v))
}

// SyncStatus applies equality check predicate on the "sync_status" field. It's identical to SyncStatusEQ.
func SyncStatus(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEQ(FieldSyncStatus, vc))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastErrorMsg applies equality check predicate on the "last_error_msg" field. It's identical to LastErrorMsgEQ.
func LastErrorMsg(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldLastErrorMsg, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEQ(FieldEntityType, vc))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldEntityType, vc))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...types.EntityType) predicate.IntegrationEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.IntegrationEntity(sql.FieldIn(FieldEntityType, v...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...types.EntityType) predicate.IntegrationEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldEntityType, v...))
}

// EntityTypeGT applies the GT predicate on the "entity_type" field.
func EntityTypeGT(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldGT(FieldEntityType, vc))
}

// EntityTypeGTE applies the GTE predicate on the "entity_type" field.
func EntityTypeGTE(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldGTE(FieldEntityType, vc))
}

// EntityTypeLT applies the LT predicate on the "entity_type" field.
func EntityTypeLT(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldLT(FieldEntityType, vc))
}

// EntityTypeLTE applies the LTE predicate on the "entity_type" field.
func EntityTypeLTE(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldLTE(FieldEntityType, vc))
}

// EntityTypeContains applies the Contains predicate on the "entity_type" field.
func EntityTypeContains(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldContains(FieldEntityType, vc))
}

// EntityTypeHasPrefix applies the HasPrefix predicate on the "entity_type" field.
func EntityTypeHasPrefix(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldEntityType, vc))
}

// EntityTypeHasSuffix applies the HasSuffix predicate on the "entity_type" field.
func EntityTypeHasSuffix(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldEntityType, vc))
}

// EntityTypeEqualFold applies the EqualFold predicate on the "entity_type" field.
func EntityTypeEqualFold(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldEntityType, vc))
}

// EntityTypeContainsFold applies the ContainsFold predicate on the "entity_type" field.
func EntityTypeContainsFold(v types.EntityType) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldEntityType, vc))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldEntityID, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEQ(FieldProviderType, vc))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldProviderType, vc))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...types.SecretProvider) predicate.IntegrationEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.IntegrationEntity(sql.FieldIn(FieldProviderType, v...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...types.SecretProvider) predicate.IntegrationEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldProviderType, v...))
}

// ProviderTypeGT applies the GT predicate on the "provider_type" field.
func ProviderTypeGT(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldGT(FieldProviderType, vc))
}

// ProviderTypeGTE applies the GTE predicate on the "provider_type" field.
func ProviderTypeGTE(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldGTE(FieldProviderType, vc))
}

// ProviderTypeLT applies the LT predicate on the "provider_type" field.
func ProviderTypeLT(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldLT(FieldProviderType, vc))
}

// ProviderTypeLTE applies the LTE predicate on the "provider_type" field.
func ProviderTypeLTE(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldLTE(FieldProviderType, vc))
}

// ProviderTypeContains applies the Contains predicate on the "provider_type" field.
func ProviderTypeContains(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldContains(FieldProviderType, vc))
}

// ProviderTypeHasPrefix applies the HasPrefix predicate on the "provider_type" field.
func ProviderTypeHasPrefix(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldProviderType, vc))
}

// ProviderTypeHasSuffix applies the HasSuffix predicate on the "provider_type" field.
func ProviderTypeHasSuffix(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldProviderType, vc))
}

// ProviderTypeEqualFold applies the EqualFold predicate on the "provider_type" field.
func ProviderTypeEqualFold(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldProviderType, vc))
}

// ProviderTypeContainsFold applies the ContainsFold predicate on the "provider_type" field.
func ProviderTypeContainsFold(v types.SecretProvider) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldProviderType, vc))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldProviderID, v))
}

// ProviderIDContains applies the Contains predicate on the "provider_id" field.
func ProviderIDContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldProviderID, v))
}

// ProviderIDHasPrefix applies the HasPrefix predicate on the "provider_id" field.
func ProviderIDHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldProviderID, v))
}

// ProviderIDHasSuffix applies the HasSuffix predicate on the "provider_id" field.
func ProviderIDHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldProviderID, v))
}

// ProviderIDIsNil applies the IsNil predicate on the "provider_id" field.
func ProviderIDIsNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIsNull(FieldProviderID))
}

// ProviderIDNotNil applies the NotNil predicate on the "provider_id" field.
func ProviderIDNotNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotNull(FieldProviderID))
}

// ProviderIDEqualFold applies the EqualFold predicate on the "provider_id" field.
func ProviderIDEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldProviderID, v))
}

// ProviderIDContainsFold applies the ContainsFold predicate on the "provider_id" field.
func ProviderIDContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldProviderID, v))
}

// SyncStatusEQ applies the EQ predicate on the "sync_status" field.
func SyncStatusEQ(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEQ(FieldSyncStatus, vc))
}

// SyncStatusNEQ applies the NEQ predicate on the "sync_status" field.
func SyncStatusNEQ(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldSyncStatus, vc))
}

// SyncStatusIn applies the In predicate on the "sync_status" field.
func SyncStatusIn(vs ...types.SyncStatus) predicate.IntegrationEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.IntegrationEntity(sql.FieldIn(FieldSyncStatus, v...))
}

// SyncStatusNotIn applies the NotIn predicate on the "sync_status" field.
func SyncStatusNotIn(vs ...types.SyncStatus) predicate.IntegrationEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldSyncStatus, v...))
}

// SyncStatusGT applies the GT predicate on the "sync_status" field.
func SyncStatusGT(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldGT(FieldSyncStatus, vc))
}

// SyncStatusGTE applies the GTE predicate on the "sync_status" field.
func SyncStatusGTE(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldGTE(FieldSyncStatus, vc))
}

// SyncStatusLT applies the LT predicate on the "sync_status" field.
func SyncStatusLT(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldLT(FieldSyncStatus, vc))
}

// SyncStatusLTE applies the LTE predicate on the "sync_status" field.
func SyncStatusLTE(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldLTE(FieldSyncStatus, vc))
}

// SyncStatusContains applies the Contains predicate on the "sync_status" field.
func SyncStatusContains(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldContains(FieldSyncStatus, vc))
}

// SyncStatusHasPrefix applies the HasPrefix predicate on the "sync_status" field.
func SyncStatusHasPrefix(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldSyncStatus, vc))
}

// SyncStatusHasSuffix applies the HasSuffix predicate on the "sync_status" field.
func SyncStatusHasSuffix(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldSyncStatus, vc))
}

// SyncStatusEqualFold applies the EqualFold predicate on the "sync_status" field.
func SyncStatusEqualFold(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldSyncStatus, vc))
}

// SyncStatusContainsFold applies the ContainsFold predicate on the "sync_status" field.
func SyncStatusContainsFold(v types.SyncStatus) predicate.IntegrationEntity {
	vc := string(v)
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldSyncStatus, vc))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotNull(FieldLastSyncedAt))
}

// LastErrorMsgEQ applies the EQ predicate on the "last_error_msg" field.
func LastErrorMsgEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEQ(FieldLastErrorMsg, v))
}

// LastErrorMsgNEQ applies the NEQ predicate on the "last_error_msg" field.
func LastErrorMsgNEQ(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNEQ(FieldLastErrorMsg, v))
}

// LastErrorMsgIn applies the In predicate on the "last_error_msg" field.
func LastErrorMsgIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIn(FieldLastErrorMsg, vs...))
}

// LastErrorMsgNotIn applies the NotIn predicate on the "last_error_msg" field.
func LastErrorMsgNotIn(vs ...string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotIn(FieldLastErrorMsg, vs...))
}

// LastErrorMsgGT applies the GT predicate on the "last_error_msg" field.
func LastErrorMsgGT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGT(FieldLastErrorMsg, v))
}

// LastErrorMsgGTE applies the GTE predicate on the "last_error_msg" field.
func LastErrorMsgGTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldGTE(FieldLastErrorMsg, v))
}

// LastErrorMsgLT applies the LT predicate on the "last_error_msg" field.
func LastErrorMsgLT(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLT(FieldLastErrorMsg, v))
}

// LastErrorMsgLTE applies the LTE predicate on the "last_error_msg" field.
func LastErrorMsgLTE(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldLTE(FieldLastErrorMsg, v))
}

// LastErrorMsgContains applies the Contains predicate on the "last_error_msg" field.
func LastErrorMsgContains(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContains(FieldLastErrorMsg, v))
}

// LastErrorMsgHasPrefix applies the HasPrefix predicate on the "last_error_msg" field.
func LastErrorMsgHasPrefix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasPrefix(FieldLastErrorMsg, v))
}

// LastErrorMsgHasSuffix applies the HasSuffix predicate on the "last_error_msg" field.
func LastErrorMsgHasSuffix(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldHasSuffix(FieldLastErrorMsg, v))
}

// LastErrorMsgIsNil applies the IsNil predicate on the "last_error_msg" field.
func LastErrorMsgIsNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldIsNull(FieldLastErrorMsg))
}

// LastErrorMsgNotNil applies the NotNil predicate on the "last_error_msg" field.
func LastErrorMsgNotNil() predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldNotNull(FieldLastErrorMsg))
}

// LastErrorMsgEqualFold applies the EqualFold predicate on the "last_error_msg" field.
func LastErrorMsgEqualFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldEqualFold(FieldLastErrorMsg, v))
}

// LastErrorMsgContainsFold applies the ContainsFold predicate on the "last_error_msg" field.
func LastErrorMsgContainsFold(v string) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.FieldContainsFold(FieldLastErrorMsg, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntegrationEntity) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntegrationEntity) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntegrationEntity) predicate.IntegrationEntity {
	return predicate.IntegrationEntity(sql.NotPredicates(p))
}
